// ------------- 100 COLECIONÁVEIS -------------
// [nome, ícone, categoria, história]
const ITEM_RAW = {
 brasil:[
  ['Berimbau de Mestre','🏹','Instrumento','Arco musical com cabaça que comanda o ritmo e a velocidade do jogo na roda de capoeira.'],
  ['Atabaque do Terreiro','🥁','Instrumento','Tambor de couro tocado com as mãos, presente no samba de roda, na capoeira e em celebrações afro-brasileiras.'],
  ['Abadá de Formatura','👕','Roupa','Uniforme branco da capoeira. Esta tem a assinatura de todos os colegas de roda de Luana.'],
  ['Turbante de Baiana','🧣','Roupa','As baianas de acarajé foram reconhecidas como patrimônio imaterial pelo Iphan em 2004, junto com o seu ofício.'],
  ['Tabuleiro de Acarajé','🍤','Receita','Bolinho de feijão-fradinho frito no azeite de dendê, com origem na culinária iorubá.'],
  ['Surdo de Bloco Afro','🪘','Instrumento','O tambor grave que marca o passo dos blocos afro de Salvador, como Ilê Aiyê e Olodum.'],
  ['Página de "Quarto de Despejo"','📖','Livro','Carolina Maria de Jesus escreveu seu diário em cadernos achados no lixo. O livro virou best-seller em 1960.'],
  ['Pena de Machado','🪶','Objeto histórico','Uma pena simbólica em homenagem a Machado de Assis, fundador da Academia Brasileira de Letras.'],
  ['Fita do Bonfim','🎗️','Símbolo','Amarrada no pulso com três nós, cada um para um desejo. Só pode ser tirada quando se rompe sozinha.'],
  ['Mapa do Quilombo','🗺️','Objeto histórico','Os quilombos eram comunidades livres. Palmares, na Serra da Barriga, resistiu por quase um século.'],
  ['Foto do Desfile','📷','Fotografia','Foto fictícia da mãe de Kayo desfilando no bloco da Vila Baobá, restaurada pelo Livro Sankofa.'],
  ['Tablet Holográfico de André','📲','Instrumento científico','O tablet onde André Cruz guarda o backup do acervo da Biblioteca Viva. A Névoa não apaga o que tem backup.']],
 ocidental:[
  ['Manuscrito de Tombuctu','📜','Livro','Tombuctu guardou dezenas de milhares de manuscritos sobre astronomia, medicina, matemática e direito.'],
  ['Tecido Kente','🧵','Roupa','Tecido tradicional de Gana, feito em faixas estreitas costuradas. Cada padrão e cor tem nome e significado.'],
  ['Kora de 21 Cordas','🎸','Instrumento','Harpa-alaúde dos griots do Mali, Senegal, Gâmbia e Guiné. Soa como chuva de notas.'],
  ['Djembê','🥁','Instrumento','Tambor em forma de cálice da África Ocidental. Dizem que tem três vozes: grave, tom e estalo.'],
  ['Símbolo Sankofa','🐦','Símbolo','Símbolo adinkra dos povos akan: um pássaro que olha para trás. Volte e busque o que ficou.'],
  ['Carimbo Adinkra','🔶','Artefato cultural','Carimbo esculpido em cabaça usado para estampar símbolos adinkra em tecidos.'],
  ['Moeda de Cauri','🐚','Artefato cultural','Conchas de cauri foram usadas como moeda em várias regiões da África por séculos.'],
  ['Mapa de Mansa Musa','🧭','Objeto histórico','O imperador do Mali ficou famoso pela peregrinação a Meca em 1324, com tanta riqueza que marcou a história.'],
  ['Mesquita de Djenné (miniatura)','🕌','Obra de arte','A maior construção de adobe do mundo. A comunidade reboca as paredes todo ano numa grande festa.'],
  ['Vinil de Afrobeat','💿','Música','Fela Kuti criou o afrobeat na Nigéria misturando highlife, jazz e funk com letras políticas.'],
  ['Jollof da Disputa','🍛','Receita','Arroz com tomate e pimenta. Gana e Nigéria discutem com carinho qual país faz o melhor.'],
  ['Máscara de Bronze do Benin','🗿','Obra de arte','Os bronzes do Reino do Benin são obras-primas de fundição. Vários estão sendo devolvidos à Nigéria.']],
 caribe:[
  ['Steel Pan','🥘','Instrumento','Criado em Trinidad e Tobago a partir de barris de petróleo, é um dos instrumentos acústicos mais novos do século XX.'],
  ['Caixa de Sound System','🔊','Música','Os sound systems jamaicanos das ruas de Kingston foram a base do reggae, do dub e da cultura DJ.'],
  ['Soup Joumou','🍲','Receita','Sopa de abóbora que os haitianos tomam todo 1º de janeiro para celebrar a independência de 1804.'],
  ['Bandeira de 1804','🚩','Objeto histórico','O Haiti foi a primeira república negra independente das Américas.'],
  ['Clave Cubana','🎵','Instrumento','Duas varetas de madeira que marcam o padrão rítmico no coração da música afro-cubana.'],
  ['Saia de Rumba','👗','Roupa','A rumba cubana nasceu em comunidades afro-cubanas e é patrimônio imaterial da UNESCO desde 2016.'],
  ['Câmera de Imani','📸','Fotografia','Câmera analógica com um filme cheio de festas de rua de Kingston.'],
  ['Pintura Naïf Haitiana','🖼️','Obra de arte','A pintura haitiana ficou famosa por cores vivas, mercados, florestas e cenas do cotidiano.'],
  ['Tambor Garifuna','🪘','Instrumento','Os garifunas, afro-indígenas da costa caribenha da América Central, têm música reconhecida pela UNESCO.'],
  ['Coco com Canudo','🥥','Objeto','Nada histórico. Só delicioso. Até heróis precisam de uma pausa.'],
  ['Máscara de Carnaval de Trinidad','🎭','Artefato cultural','O carnaval de Trinidad mistura calipso, soca e fantasias gigantescas.'],
  ['Disco de Ska','💿','Música','O ska surgiu na Jamaica nos anos 1950/60 e abriu caminho para o rocksteady e o reggae.']],
 eua:[
  ['Trompete de Nova Orleans','🎺','Instrumento','O jazz nasceu em Nova Orleans no começo do século XX, misturando blues, ragtime e ritmos afro-caribenhos.'],
  ['Violão de Blues','🎸','Instrumento','O blues nasceu no sul dos EUA e é a base de quase toda a música popular moderna.'],
  ['Toca-discos do Bronx','🎛️','Música','O hip-hop nasceu no Bronx nos anos 1970, em festas de bairro onde DJs estendiam as batidas dos discos.'],
  ['Spray de Grafite','🎨','Obra de arte','Um dos quatro elementos do hip-hop, ao lado do DJ, do MC e da dança break.'],
  ['Semáforo de Garrett Morgan','🚦','Instrumento científico','Garrett Morgan patenteou em 1923 um sinal de trânsito com posição de alerta.'],
  ['Pote de Madam C.J. Walker','🧴','Objeto histórico','Criou uma linha de produtos para cabelo e é citada como a primeira mulher a se tornar milionária por conta própria nos EUA.'],
  ['Cálculos de Katherine Johnson','📐','Instrumento científico','A matemática da NASA calculou trajetórias para missões espaciais históricas.'],
  ['Luva Mecânica de Marcus','🦾','Instrumento científico','Protótipo montado com peças de carro de Detroit. Funciona. Às vezes.'],
  ['Disco de Soul de Detroit','💿','Música','Detroit foi berço de uma gravadora lendária que levou a soul para o mundo nos anos 1960.'],
  ['Colcha de Retalhos','🧶','Artefato cultural','As colchas de Gee\'s Bend, no Alabama, feitas por mulheres negras, hoje estão em museus de arte.'],
  ['Microfone de Rima','🎤','Música','O MC comanda a festa. Rimar é contar histórias em cima do ritmo.'],
  ['Tênis de Break','👟','Roupa','O breaking nasceu nas festas de hip-hop e estreou como esporte olímpico em Paris 2024.']],
 austral:[
  ['Pedra do Grande Zimbábue','🪨','Objeto histórico','As muralhas foram erguidas sem argamassa, entre os séculos XI e XV.'],
  ['Pássaro de Pedra-sabão','🦅','Obra de arte','Esculturas de pássaros achadas no Grande Zimbábue. Uma delas está na bandeira do país.'],
  ['Rinoceronte de Ouro','🦏','Artefato cultural','Pequena escultura de ouro de Mapungubwe, reino que floresceu antes do Grande Zimbábue.'],
  ['Log Drum de Amapiano','🥁','Música','O amapiano, nascido na África do Sul nos anos 2010, tem um grave percussivo inconfundível.'],
  ['Bastões de Luta','🥢','Artefato cultural','A luta com bastões é tradição nguni de habilidade, disciplina e respeito.'],
  ['Colar de Contas Zulu','📿','Joia','No trabalho de contas zulu, cores e padrões podem transmitir mensagens.'],
  ['Caderno de Campo de Thabo','📓','Livro','Cada pedra desenhada antes de ser tocada. Primeira regra da arqueologia de Thabo.'],
  ['Placa "Ubuntu"','🤝','Símbolo','Filosofia de língua banta: uma pessoa é pessoa por meio das outras pessoas.'],
  ['Cédula Comemorativa','💵','Objeto histórico','Nelson Mandela tornou-se o primeiro presidente eleito democraticamente da África do Sul em 1994.'],
  ['Cerâmica Ndebele','🏺','Obra de arte','O povo ndebele é famoso por pinturas geométricas vibrantes em casas e objetos.'],
  ['Bunny Chow','🍞','Receita','Pão oco recheado com curry, criado em Durban. Come-se com as mãos.'],
  ['Mbira','🎹','Instrumento','"Piano de polegar" do povo shona do Zimbábue, com lâminas metálicas sobre madeira.']],
 latina:[
  ['Tambor Alegre','🥁','Instrumento','Tambor da música de Palenque e do litoral caribenho da Colômbia.'],
  ['Trança-Mapa','💇🏾‍♀️','Símbolo','Relatos orais contam que tranças guardavam caminhos e sementes durante fugas para a liberdade.'],
  ['Estátua de Benkos Biohó','🗽','Objeto histórico','Líder que fundou San Basilio de Palenque, o primeiro povoado livre das Américas.'],
  ['Marimba de Chonta','🎼','Instrumento','A música de marimba do Pacífico colombiano e equatoriano é patrimônio da UNESCO.'],
  ['Dicionário Palenquero','📘','Livro','A língua palenquera mistura espanhol com línguas bantas e ainda é falada em Palenque.'],
  ['Vinil de Cumbia','💿','Música','A cumbia colombiana tem raízes africanas, indígenas e europeias.'],
  ['Chuteira de Valentina','👟','Roupa','Gasta de tanto treino na areia do Rio Atrato.'],
  ['Cocada Palenquera','🍬','Receita','As doceiras de Palenque vendem doces tradicionais nas ruas de Cartagena.'],
  ['Máscara de Congo','🎭','Artefato cultural','O Congo de Portobelo, no Panamá, é uma tradição afro-panamenha de teatro, dança e memória.'],
  ['Cajón Peruano','📦','Instrumento','Caixa de madeira criada por afroperuanos. Hoje é tocada no mundo todo.'],
  ['Foto da Praça de Palenque','📷','Fotografia','Crianças brincando ao redor da estátua. A cena que a Névoa quase apagou.'],
  ['Currulao','🎶','Música','Ritmo do Pacífico colombiano, com marimba, cununos e cantos em resposta.']],
 oriental:[
  ['Miniatura do Obelisco de Aksum','🗼','Objeto histórico','Aksum ergueu obeliscos enormes. Um deles, levado para Roma, voltou à Etiópia em 2005.'],
  ['Moeda de Aksum','🪙','Objeto histórico','O Reino de Aksum foi um dos primeiros da África a cunhar moedas próprias.'],
  ['Cruz de Lalibela','✝️','Obra de arte','Em Lalibela, igrejas foram esculpidas em uma única rocha, de cima para baixo.'],
  ['Cerimônia do Café','☕','Receita','Na Etiópia, o café é torrado, moído e servido em três rodadas, com calma e conversa.'],
  ['Pergaminho em Ge\'ez','📜','Livro','Ge\'ez é a antiga língua da Etiópia, com escrita própria usada até hoje em textos religiosos.'],
  ['Kanga Estampada','🧣','Roupa','Tecido da costa suaíli que costuma trazer um provérbio impresso.'],
  ['Muda do Cinturão Verde','🌱','Símbolo','Wangari Maathai, do Quênia, liderou o plantio de milhões de árvores e ganhou o Nobel da Paz em 2004.'],
  ['Tênis de Maratona','👟','Roupa','Corredores do Quênia e da Etiópia dominam as maratonas mundiais há décadas.'],
  ['Mural de Matatu','🚌','Obra de arte','Os matatus de Nairóbi são micro-ônibus decorados com grafite, luz e som.'],
  ['Krar','🪕','Instrumento','Lira de cinco ou seis cordas tocada na Etiópia e na Eritreia.'],
  ['Porta Entalhada de Zanzibar','🚪','Artefato cultural','As portas de madeira entalhada de Stone Town misturam influências africanas, árabes e indianas.'],
  ['Dicionário Suaíli','📗','Livro','O suaíli é uma das línguas mais faladas da África. "Hakuna matata" quer dizer "sem problemas".']],
 futuro:[
  ['Tecido de Grafeno Kente','🧬','Roupa','Tecido inteligente de Neo-Axé que muda de padrão conforme a música.'],
  ['Holograma da Universidade','🏛️','Objeto','A Universidade de Neo-Axé homenageia Sankoré, de Tombuctu, com um arquivo aberto.'],
  ['Capacete de Ayana','🪖','Instrumento científico','Viseira que mostra constelações usadas por povos antigos para navegar.'],
  ['Drone Jardineiro','🛸','Instrumento científico','Planta árvores nos telhados. Inspirado no Cinturão Verde.'],
  ['Sintetizador Afrofuturo','🎹','Música','Mistura samples de kora, surdo e steel pan com sons eletrônicos.'],
  ['Cristal de Memória','💎','Artefato cultural','Guarda uma história contada por uma avó. Nunca apaga.'],
  ['Moto Magnética','🏍️','Objeto','Veículo de Neo-Axé com padrões geométricos pintados à mão.'],
  ['Máscara Holográfica','🎭','Obra de arte','Arte digital inspirada em máscaras tradicionais, criada com a permissão das comunidades.'],
  ['Mapa Estelar Dogon','🌌','Objeto histórico','Os dogons, do Mali, têm uma rica tradição de conhecimento sobre o céu, ainda debatida por pesquisadores.'],
  ['Chip de Backup Pan-africano','💾','Instrumento científico','Backup do arquivo em cinco continentes. A lição que Vulcano ensinou.'],
  ['Colar Neon','📿','Joia','Contas que acendem conforme o batimento de quem usa.'],
  ['Placa da Estação Orbital','🛰️','Objeto','Primeira estação de Neo-Axé. Nome escolhido por votação das escolas.']],
 legado:[
  ['Livro Sankofa','📕','Artefato cultural','O livro que abre portais para as memórias do mundo. Guardado pela avó de Kayo.'],
  ['Folha do Baobá','🍃','Símbolo','O baobá pode viver por séculos. Na Vila, é onde todos se reúnem.'],
  ['Coroa de Kayo','👑','Joia','Não é de realeza. É o símbolo da Vila: cada pessoa é importante.'],
  ['Página Restaurada','📄','Livro','A última página do livro. Está em branco de propósito: é sua para escrever.']]
};
const ITEMS=[]; for(const r in ITEM_RAW) ITEM_RAW[r].forEach((it,i)=>ITEMS.push({id:r+'_'+i, region:r, name:it[0], ic:it[1], cat:it[2], story:it[3]}));
const IT = Object.fromEntries(ITEMS.map(i=>[i.id,i]));

// ------------- QUIZ CULTURAL -------------
// Cada pergunta pertence a uma região do mapa (r). A resposta certa é sempre a primeira opção (o[0]);
// o jogo embaralha as opções. "why" é a explicação mostrada depois da resposta.
const QUIZ = [
 // ---------- BRASIL (Salvador & Rio) ----------
 {r:'brasil', q:'Em que ano a roda de capoeira foi reconhecida como patrimônio da humanidade pela UNESCO?', o:['2014','1988','2001','2020'],
  why:'Em novembro de 2014 a UNESCO incluiu a roda de capoeira na lista do Patrimônio Cultural Imaterial da Humanidade, reconhecendo a luta, a música e a roda como herança afro-brasileira.'},
 {r:'brasil', q:'Qual instrumento comanda o ritmo da roda de capoeira?', o:['Berimbau','Cavaquinho','Kora','Steel pan'],
  why:'O berimbau, um arco de madeira com cabaça, puxa o toque da roda. O toque define a velocidade e o estilo do jogo, e os capoeiristas seguem o que ele manda.'},
 {r:'brasil', q:'Salvador, onde fica o Pelourinho, foi a primeira capital do Brasil. Até que ano?', o:['1763','1822','1500','1889'],
  why:'Salvador foi capital de 1549 a 1763, quando a sede do governo passou para o Rio de Janeiro. Por isso a cidade guarda um dos maiores conjuntos coloniais das Américas.'},
 {r:'brasil', q:'Qual é considerado o primeiro bloco afro do Brasil, fundado em Salvador em 1974?', o:['Ilê Aiyê','Olodum','Filhos de Gandhy','Timbalada'],
  why:'O Ilê Aiyê nasceu em 1974 no bairro da Liberdade (Curuzu) para celebrar a beleza e a cultura negra no Carnaval. Ele abriu caminho para outros blocos afro, como o Olodum (1979).'},
 {r:'brasil', q:'O Dia Nacional de Zumbi e da Consciência Negra no Brasil é em...', o:['20 de novembro','13 de maio','7 de setembro','25 de julho'],
  why:'20 de novembro de 1695 é a data da morte de Zumbi dos Palmares, líder do maior quilombo das Américas. Em 2023 a data virou feriado nacional.'},
 {r:'brasil', q:'O Quilombo dos Palmares ficava na Serra da Barriga, em qual estado de hoje?', o:['Alagoas','Bahia','Minas Gerais','Maranhão'],
  why:'Palmares resistiu por quase cem anos na Serra da Barriga, em Alagoas, reunindo milhares de pessoas que fugiram da escravidão. Hoje o local é o Parque Memorial Quilombo dos Palmares.'},
 {r:'brasil', q:'Quem fundou a Academia Brasileira de Letras e foi seu primeiro presidente?', o:['Machado de Assis','Lima Barreto','Castro Alves','Cruz e Sousa'],
  why:'Machado de Assis, escritor negro nascido no Rio de Janeiro, ajudou a fundar a Academia em 1897 e foi o primeiro presidente. É considerado um dos maiores autores da língua portuguesa.'},
 {r:'brasil', q:'"Quarto de Despejo" foi escrito por...', o:['Carolina Maria de Jesus','Conceição Evaristo','Cecília Meireles','Clarice Lispector'],
  why:'Carolina Maria de Jesus escreveu o diário da sua vida na favela do Canindé, em São Paulo. Publicado em 1960, virou best-seller e foi traduzido para mais de dez idiomas.'},
 {r:'brasil', q:'A jogadora Marta foi eleita melhor do mundo pela FIFA quantas vezes?', o:['6','2','10','4'],
  why:'Marta ganhou o prêmio em 2006, 2007, 2008, 2009, 2010 e 2018. Ela também é a maior artilheira da história das Copas do Mundo, somando homens e mulheres.'},
 {r:'brasil', q:'Qual manifestação do Recôncavo Baiano foi reconhecida pela UNESCO em 2005 e é uma das raízes do samba?', o:['Samba de roda','Frevo','Bumba meu boi','Maracatu'],
  why:'O samba de roda, com palmas, prato e faca, viola e dança em círculo, é tradição das comunidades negras do Recôncavo. A UNESCO o reconheceu em 2005.'},

 // ---------- ÁFRICA OCIDENTAL (Tombuctu & Acra) ----------
 {r:'ocidental', q:'O que significa "Sankofa", símbolo dos povos akan?', o:['Volte e busque o que ficou para trás','Siga sempre em frente','A força do trovão','Casa grande'],
  why:'Sankofa vem da língua akan, de Gana. O símbolo é um pássaro olhando para trás: aprender com o passado para construir o futuro.'},
 {r:'ocidental', q:'Em que cidade africana ficavam milhares de manuscritos antigos de ciência e direito?', o:['Tombuctu','Cairo','Luanda','Dacar'],
  why:'Tombuctu, no Mali, foi um grande centro de estudos entre os séculos XIII e XVI. Suas bibliotecas guardaram manuscritos de astronomia, matemática, medicina e direito.'},
 {r:'ocidental', q:'Qual desses reinos ficou famoso pelo imperador Mansa Musa?', o:['Império do Mali','Reino de Aksum','Reino do Congo','Grande Zimbábue'],
  why:'Mansa Musa governou o Império do Mali no século XIV. Na peregrinação a Meca, em 1324, levou tanto ouro que mudou o preço do metal no Cairo.'},
 {r:'ocidental', q:'O afrobeat foi criado por Fela Kuti em qual país?', o:['Nigéria','Gana','Senegal','Quênia'],
  why:'Fela Kuti misturou highlife, jazz, funk e ritmos iorubás em Lagos, na Nigéria, no fim dos anos 1960. Suas letras criticavam a corrupção e a opressão.'},
 {r:'ocidental', q:'Qual ritmo nasceu em Gana e influenciou o afrobeat?', o:['Highlife','Samba','Tango','Reggaeton'],
  why:'O highlife surgiu em Gana no início do século XX, misturando ritmos locais com metais e violões. Fela Kuti tocou highlife antes de criar o afrobeat.'},
 {r:'ocidental', q:'O tecido kente é tradicional de qual país?', o:['Gana','Marrocos','Angola','Moçambique'],
  why:'O kente é tecido em tiras estreitas pelos povos ashanti e ewe, em Gana. Cada cor e padrão tem significado, como ouro para riqueza e verde para crescimento.'},
 {r:'ocidental', q:'A kora, harpa dos griôs, tem quantas cordas tradicionalmente?', o:['21','6','4','12'],
  why:'A kora tradicional tem 21 cordas presas a uma grande cabaça coberta de couro. É tocada pelos griôs mandingas do Mali, Senegal, Gâmbia e Guiné.'},
 {r:'ocidental', q:'Na África Ocidental, quem são os griôs?', o:['Guardiões da história contada e cantada','Guardas do palácio','Comerciantes de sal','Construtores de mesquitas'],
  why:'Os griôs guardam a memória dos povos pela palavra e pela música: genealogias, feitos de reis e histórias da comunidade, passadas de geração em geração.'},
 {r:'ocidental', q:'Em 1957, Gana se tornou independente do Reino Unido. Quem liderou o país?', o:['Kwame Nkrumah','Nelson Mandela','Patrice Lumumba','Jomo Kenyatta'],
  why:'Kwame Nkrumah liderou a luta pela independência e foi o primeiro chefe de governo de Gana. Também foi um dos grandes nomes do pan-africanismo.'},
 {r:'ocidental', q:'A Grande Mesquita de Djenné, no Mali, é famosa por ser...', o:['A maior construção de barro do mundo','Feita toda de mármore','Flutuante sobre o rio Níger','A mais alta da África'],
  why:'A mesquita é feita de adobe (tijolos de barro secos ao sol). Todo ano a comunidade se junta numa festa para rebocar as paredes com barro novo.'},

 // ---------- CARIBE (Kingston, Havana & Porto Príncipe) ----------
 {r:'caribe', q:'Qual país foi a primeira república negra independente das Américas, em 1804?', o:['Haiti','Jamaica','Cuba','Brasil'],
  why:'Depois de uma revolução iniciada em 1791 por pessoas escravizadas, o Haiti declarou a independência da França em 1º de janeiro de 1804.'},
 {r:'caribe', q:'Quem foi o principal líder da Revolução Haitiana?', o:['Toussaint Louverture','Simón Bolívar','Marcus Garvey','José Martí'],
  why:'Toussaint Louverture, que nasceu escravizado, liderou o exército revolucionário e organizou o governo. Ele morreu preso na França em 1803, um ano antes da independência.'},
 {r:'caribe', q:'O reggae nasceu em qual país?', o:['Jamaica','Cuba','Trinidad e Tobago','Bahamas'],
  why:'O reggae surgiu na Jamaica no fim dos anos 1960 e ganhou o mundo com Bob Marley. Em 2018 a UNESCO o reconheceu como patrimônio da humanidade.'},
 {r:'caribe', q:'Qual ritmo jamaicano veio antes do reggae, nos anos 1950 e 1960?', o:['Ska','Salsa','Bossa nova','Merengue'],
  why:'O ska nasceu em Kingston misturando mento, jazz e R&B. Depois ficou mais lento e virou rocksteady, que deu origem ao reggae.'},
 {r:'caribe', q:'Os "sound systems", paredões de caixas de som que levavam música às ruas, ficaram famosos em qual cidade?', o:['Kingston','Havana','Miami','Porto Príncipe'],
  why:'Nos anos 1950, DJs de Kingston montavam enormes sistemas de som para festas de rua. Essa cultura chegou ao Bronx e ajudou a criar o hip-hop.'},
 {r:'caribe', q:'O steel pan foi criado em qual país?', o:['Trinidad e Tobago','Barbados','Haiti','Porto Rico'],
  why:'O steel pan foi criado em Trinidad e Tobago entre os anos 1930 e 1940, a partir de tambores de óleo descartados. Hoje é o instrumento nacional do país.'},
 {r:'caribe', q:'A rumba cubana foi reconhecida pela UNESCO em que ano?', o:['2016','1959','1990','2022'],
  why:'Em 2016 a UNESCO reconheceu a rumba, nascida nos bairros afro-cubanos de Havana e Matanzas, que junta tambores, canto e dança.'},
 {r:'caribe', q:'Celia Cruz, a "Rainha da Salsa", nasceu em qual cidade?', o:['Havana','Kingston','San Juan','Santo Domingo'],
  why:'Celia Cruz nasceu em Havana, Cuba, em 1925. Com seu grito "¡Azúcar!" levou a música afro-cubana para o mundo inteiro.'},
 {r:'caribe', q:'Marcus Garvey, líder do pan-africanismo, nasceu em qual país?', o:['Jamaica','Haiti','Estados Unidos','Gana'],
  why:'Garvey nasceu na Jamaica em 1887 e fundou a UNIA em 1914, um movimento de orgulho negro que chegou a ter milhões de seguidores.'},
 {r:'caribe', q:'O calipso, música do Carnaval caribenho, nasceu em qual país?', o:['Trinidad e Tobago','Cuba','Jamaica','Haiti'],
  why:'O calipso vem das canções dos povos africanos escravizados em Trinidad e virou a trilha do Carnaval da ilha, com letras de crítica e humor.'},

 // ---------- ESTADOS UNIDOS (Nova Orleans, Detroit & Bronx) ----------
 {r:'eua', q:'Onde nasceu o jazz?', o:['Nova Orleans','Chicago','Paris','Detroit'],
  why:'O jazz nasceu em Nova Orleans no início do século XX, misturando blues, ragtime, cantos de igreja e ritmos africanos e caribenhos.'},
 {r:'eua', q:'Em Nova Orleans, qual praça reunia aos domingos pessoas escravizadas para tocar e dançar ritmos africanos?', o:['Congo Square','Times Square','Union Square','Washington Square'],
  why:'Na Congo Square, africanos e afrodescendentes se reuniam para tocar tambores e dançar. Esses encontros são considerados uma das raízes do jazz.'},
 {r:'eua', q:'Louis Armstrong, um dos maiores trompetistas do jazz, nasceu em qual cidade?', o:['Nova Orleans','Nova York','Memphis','Atlanta'],
  why:'Armstrong nasceu em Nova Orleans em 1901 e aprendeu a tocar ainda menino. Sua voz rouca e seus improvisos mudaram o jazz para sempre.'},
 {r:'eua', q:'O hip-hop surgiu nos anos 1970 em qual bairro de Nova York?', o:['Bronx','Manhattan','Queens','Staten Island'],
  why:'Em agosto de 1973, numa festa no prédio 1520 da Sedgwick Avenue, no Bronx, o DJ Kool Herc estendeu as batidas dos discos. Ali nasceu o hip-hop.'},
 {r:'eua', q:'O DJ Kool Herc, apontado como "pai do hip-hop", nasceu em qual país?', o:['Jamaica','Estados Unidos','Brasil','Nigéria'],
  why:'Kool Herc nasceu em Kingston e trouxe para o Bronx a cultura jamaicana dos sound systems. Por isso o hip-hop tem raízes no Caribe.'},
 {r:'eua', q:'A gravadora Motown, de Stevie Wonder e The Supremes, foi fundada em qual cidade?', o:['Detroit','Los Angeles','Nashville','Chicago'],
  why:'Berry Gordy fundou a Motown em Detroit em 1959. O apelido da cidade, Motor City, deu nome à gravadora que levou a soul music ao mundo.'},
 {r:'eua', q:'Qual gênero de música eletrônica foi criado por jovens negros de Detroit nos anos 1980?', o:['Techno','Reggae','Forró','Bossa nova'],
  why:'Juan Atkins, Derrick May e Kevin Saunderson criaram o techno em Detroit, inspirados pelas máquinas, pelo funk e pela ficção científica.'},
 {r:'eua', q:'Em 1955, Rosa Parks se recusou a ceder seu lugar no ônibus em qual cidade?', o:['Montgomery','Nova Orleans','Detroit','Nova York'],
  why:'A prisão de Rosa Parks em Montgomery, Alabama, iniciou um boicote aos ônibus que durou 381 dias e virou marco da luta pelos direitos civis.'},
 {r:'eua', q:'O inventor Garrett Morgan patenteou em 1923 uma versão de qual invenção?', o:['Semáforo','Telefone','Avião','Rádio'],
  why:'Garrett Morgan patenteou um semáforo de três posições que parava todos os carros antes de liberar outra direção, deixando os cruzamentos mais seguros.'},
 {r:'eua', q:'Katherine Johnson ficou conhecida por...', o:['Calcular trajetórias de voos espaciais da NASA','Fundar uma gravadora','Ganhar uma maratona olímpica','Pintar murais no Bronx'],
  why:'A matemática Katherine Johnson conferiu os cálculos do voo de John Glenn em 1962 e trabalhou na missão Apollo 11. Sua história está no filme "Estrelas Além do Tempo".'},

 // ---------- ÁFRICA AUSTRAL (Grande Zimbábue & Joanesburgo) ----------
 {r:'austral', q:'As muralhas do Grande Zimbábue foram construídas...', o:['Sem argamassa','Com concreto','Com tijolos de barro cozido','Com madeira'],
  why:'Entre os séculos XI e XV, blocos de granito foram encaixados com tanta precisão que as muralhas ficam de pé até hoje sem nenhuma argamassa.'},
 {r:'austral', q:'O nome "Zimbábue" vem da língua xona e quer dizer...', o:['Casas de pedra','Rio sagrado','Terra do ouro','Montanha alta'],
  why:'Zimbábue vem de "dzimba dza mabwe", casas de pedra em xona. O país escolheu o nome em homenagem às ruínas do Grande Zimbábue.'},
 {r:'austral', q:'Qual reino antigo da África Austral ficou famoso por um pequeno rinoceronte de ouro?', o:['Mapungubwe','Mali','Aksum','Benim'],
  why:'Mapungubwe floresceu por volta de 1075 a 1220 no vale do rio Limpopo. O rinoceronte dourado achado em um túmulo real virou símbolo da riqueza do reino.'},
 {r:'austral', q:'Qual filosofia banta diz "eu sou porque nós somos"?', o:['Ubuntu','Sankofa','Hakuna matata','Axé'],
  why:'Ubuntu é uma filosofia dos povos bantos da África Austral: ninguém existe sozinho, a nossa humanidade se faz na comunidade.'},
 {r:'austral', q:'Quem foi o primeiro presidente eleito democraticamente da África do Sul?', o:['Nelson Mandela','Desmond Tutu','Thabo Mbeki','Steve Biko'],
  why:'Em 1994, nas primeiras eleições em que toda a população pôde votar, Nelson Mandela foi eleito presidente. Era o fim oficial do apartheid.'},
 {r:'austral', q:'Por quantos anos Nelson Mandela ficou preso por lutar contra o apartheid?', o:['27','5','12','40'],
  why:'Mandela foi preso em 1962 e libertado em 1990: 27 anos, boa parte na Ilha Robben. Ao sair, liderou a transição pacífica do país.'},
 {r:'austral', q:'O amapiano é um gênero musical nascido em qual país?', o:['África do Sul','Nigéria','Brasil','Jamaica'],
  why:'O amapiano surgiu nos bairros de Pretória e Joanesburgo na década de 2010, misturando house, jazz e o grave do "log drum".'},
 {r:'austral', q:'Em 16 de junho de 1976, estudantes de Soweto protestaram contra...', o:['A obrigação de estudar em africâner','O preço do pão','A falta de estádios','O fim das férias'],
  why:'Milhares de estudantes marcharam contra o ensino obrigatório em africâner, a língua do regime do apartheid. Hoje 16 de junho é o Dia da Juventude no país.'},
 {r:'austral', q:'Miriam Makeba, voz contra o apartheid, ficou conhecida pelo apelido...', o:['Mama África','Rainha do Soul','Dama do Jazz','Voz do Sahel'],
  why:'A cantora sul-africana Miriam Makeba levou a música do seu país ao mundo e denunciou o apartheid nas Nações Unidas. Por isso ganhou o apelido Mama África.'},
 {r:'austral', q:'O arcebispo sul-africano Desmond Tutu ganhou o Nobel da Paz em que ano?', o:['1984','1964','1994','2004'],
  why:'Tutu recebeu o Nobel em 1984 pela luta não violenta contra o apartheid. Depois presidiu a Comissão da Verdade e Reconciliação.'},

 // ---------- AMÉRICA LATINA (Palenque & Pacífico colombiano) ----------
 {r:'latina', q:'San Basilio de Palenque, na Colômbia, é considerado...', o:['O primeiro povoado livre das Américas','A maior cidade da Colômbia','Uma ilha vulcânica','Um templo antigo'],
  why:'Palenque foi fundado no século XVII por pessoas que fugiram da escravidão. Elas resistiram até conseguir o reconhecimento da sua liberdade pela Coroa espanhola.'},
 {r:'latina', q:'Quem liderou a fuga e a resistência que deram origem a San Basilio de Palenque?', o:['Benkos Biohó','Zumbi dos Palmares','Toussaint Louverture','Simón Bolívar'],
  why:'Benkos Biohó escapou da escravidão em Cartagena no início dos anos 1600 e organizou o palenque nas montanhas. É herói da resistência afro-colombiana.'},
 {r:'latina', q:'A língua palenquera, falada em San Basilio de Palenque, mistura espanhol com...', o:['Línguas bantas, como o kikongo','Inglês e francês','Japonês','Latim antigo'],
  why:'O palenquero é uma língua crioula com base no espanhol e forte influência de línguas bantas da região do Congo e de Angola. É ensinada nas escolas do povoado.'},
 {r:'latina', q:'Em que ano a UNESCO reconheceu o espaço cultural de San Basilio de Palenque?', o:['2005','1810','1960','2022'],
  why:'Em 2005 a UNESCO proclamou Palenque patrimônio oral e imaterial da humanidade, pela língua, pela música e pela organização comunitária.'},
 {r:'latina', q:'Qual instrumento é o coração da música afro do Pacífico colombiano?', o:['Marimba de chonta','Bandoneón','Acordeão','Gaita de foles'],
  why:'A marimba de chonta, feita com madeira de palmeira, guia os cantos tradicionais do Pacífico Sul. A UNESCO reconheceu essa música em 2010.'},
 {r:'latina', q:'Quibdó, cidade de maioria afrodescendente no Pacífico colombiano, é capital de qual departamento?', o:['Chocó','Antioquia','Bolívar','Nariño'],
  why:'Quibdó é a capital do Chocó, região de floresta e rios onde a maioria da população é afro-colombiana. É a terra da Valentina no jogo.'},
 {r:'latina', q:'A champeta, ritmo dançante com influência da música africana, nasceu em quais lugares?', o:['Cartagena e Palenque','Buenos Aires e Montevidéu','Lima e Cusco','Cidade do México'],
  why:'A champeta surgiu nos bairros populares de Cartagena e em Palenque, inspirada em discos africanos de soukous e highlife que chegavam pelo porto.'},
 {r:'latina', q:'Qual festival em Cali celebra todo ano a música do Pacífico colombiano?', o:['Petronio Álvarez','Rock in Rio','Festival de Viña del Mar','Carnaval de Barranquilla'],
  why:'O Festival Petronio Álvarez acontece em Cali desde 1997 e reúne grupos de marimba, cantoras e chirimías de todo o Pacífico.'},
 {r:'latina', q:'Os garífunas, povo afro-indígena da América Central, tiveram sua língua, dança e música reconhecidas pela UNESCO em que ano?', o:['2001','1950','2015','2023'],
  why:'Em 2001 a UNESCO reconheceu a cultura garífuna, que vive em Honduras, Belize, Guatemala e Nicarágua e nasceu do encontro de africanos com povos indígenas caribenhos.'},
 {r:'latina', q:'Em 2019, qual país reconheceu os povos afrodescendentes na sua Constituição?', o:['México','Colômbia','Peru','Chile'],
  why:'Em 2019 o México incluiu os povos e comunidades afro-mexicanas na Constituição, um reconhecimento cobrado havia décadas, principalmente na Costa Chica.'},

 // ---------- ÁFRICA ORIENTAL (Aksum, Lalibela & Nairóbi) ----------
 {r:'oriental', q:'Em Lalibela, na Etiópia, as igrejas foram...', o:['Esculpidas em uma única rocha','Feitas de bambu','Construídas flutuando num lago','Pintadas de ouro'],
  why:'Onze igrejas foram escavadas de cima para baixo na rocha vulcânica nos séculos XII e XIII, a mando do rei Lalibela. São Patrimônio da UNESCO desde 1978.'},
 {r:'oriental', q:'O Reino de Aksum foi um dos primeiros da África a...', o:['Cunhar suas próprias moedas','Usar trens','Construir arranha-céus','Fabricar papel'],
  why:'Aksum cunhava moedas de ouro, prata e bronze desde o século III e comerciava com Roma, Índia e Arábia. Também ergueu enormes obeliscos de pedra.'},
 {r:'oriental', q:'Em 1896, a Etiópia venceu a Itália e manteve sua independência na Batalha de...', o:['Adwa','Waterloo','Isandlwana','Palmares'],
  why:'Na Batalha de Adwa, o imperador Menelik II e a imperatriz Taytu derrotaram o exército italiano. A Etiópia virou símbolo de liberdade para toda a África.'},
 {r:'oriental', q:'Qual país africano tem mais pirâmides antigas que o Egito?', o:['Sudão','Etiópia','Mali','Nigéria'],
  why:'O Sudão, terra dos antigos reinos núbios, tem mais de 200 pirâmides, como as de Meroé, mais que o Egito. São menores e mais pontiagudas.'},
 {r:'oriental', q:'Wangari Maathai, que ganhou o Nobel da Paz em 2004, era de qual país?', o:['Quênia','Etiópia','Uganda','Tanzânia'],
  why:'A queniana Wangari Maathai criou o Movimento Cinturão Verde, que plantou dezenas de milhões de árvores. Foi a primeira mulher africana a ganhar o Nobel da Paz.'},
 {r:'oriental', q:'Abebe Bikila, da Etiópia, ganhou a maratona olímpica de Roma em 1960 de um jeito marcante. Como?', o:['Correndo descalço','De bicicleta','Andando de costas','Com uma bandeira na mão'],
  why:'Bikila correu os 42 km descalço e venceu, tornando-se o primeiro africano negro campeão olímpico. Em 1964, em Tóquio, ganhou de novo, desta vez de tênis.'},
 {r:'oriental', q:'O queniano Eliud Kipchoge ficou famoso em 2019 por...', o:['Correr uma maratona em menos de 2 horas','Escalar o Everest','Nadar o Atlântico','Pilotar um foguete'],
  why:'Em Viena, Kipchoge completou 42 km em 1h59min40s, algo que muitos achavam impossível. A marca não vale como recorde oficial por causa do esquema especial da prova.'},
 {r:'oriental', q:'Segundo a tradição, qual bebida famosa teve origem nas terras altas da Etiópia?', o:['Café','Chá-preto','Chocolate','Guaraná'],
  why:'O café arábica é nativo das florestas do sudoeste da Etiópia, na região de Kaffa. Até hoje o país tem uma cerimônia tradicional do café.'},
 {r:'oriental', q:'Qual língua, muito falada no Quênia e na Tanzânia, usa a palavra "jambo" para dizer olá?', o:['Suaíli','Iorubá','Zulu','Amárico'],
  why:'O suaíli é uma língua banta com muitas palavras de origem árabe, falada por mais de 100 milhões de pessoas na África Oriental.'},
 {r:'oriental', q:'Mulatu Astatke é considerado o "pai" de qual estilo musical?', o:['Ethio-jazz','Amapiano','Reggae','Samba-rock'],
  why:'Nos anos 1960 e 1970, Mulatu Astatke juntou as escalas da música etíope com jazz e ritmos latinos, criando o ethio-jazz.'},

 // ---------- NEO-AXÉ (afrofuturismo, ciência e invenção) ----------
 {r:'futuro', q:'Em que ano o termo "afrofuturismo" foi criado?', o:['1993','1804','1960','2018'],
  why:'O crítico Mark Dery usou a palavra em 1993 para falar da arte que imagina o futuro a partir da cultura e da história negras.'},
 {r:'futuro', q:'Mae Jemison entrou para a história em 1992 por ser...', o:['A primeira mulher negra no espaço','A primeira presidente dos EUA','Campeã olímpica de natação','Fundadora de uma gravadora'],
  why:'A médica e engenheira Mae Jemison voou no ônibus espacial Endeavour em setembro de 1992 e passou mais de uma semana em órbita.'},
 {r:'futuro', q:'O músico Sun Ra, pioneiro do afrofuturismo, dizia ter vindo de qual planeta?', o:['Saturno','Marte','Vênus','Netuno'],
  why:'Sun Ra criou um personagem vindo de Saturno e misturava jazz, figurinos espaciais e mitologia egípcia. Seu filme "Space Is the Place" é um clássico do afrofuturismo.'},
 {r:'futuro', q:'Octavia E. Butler, autora de "Kindred" e "A Parábola do Semeador", ficou famosa em qual gênero?', o:['Ficção científica','Poesia romântica','Livros de receitas','Teatro de comédia'],
  why:'Butler usou a ficção científica para falar de raça, poder e sobrevivência. Em 1995 foi a primeira autora do gênero a receber a bolsa MacArthur.'},
 {r:'futuro', q:'O matemático Ron Eglash mostrou que muitas aldeias, tranças e tecidos africanos seguem padrões chamados...', o:['Fractais','Triângulos retos','Linhas paralelas','Círculos perfeitos'],
  why:'Fractais são formas que se repetem em escalas diferentes. Eglash encontrou esse padrão no desenho de aldeias, esculturas e penteados africanos.'},
 {r:'futuro', q:'O trabalho da matemática Gladys West foi base para qual tecnologia usada até hoje?', o:['GPS','Micro-ondas','Televisão','Telefone fixo'],
  why:'Gladys West criou modelos muito precisos do formato da Terra a partir de dados de satélite. Esses modelos foram essenciais para o sistema GPS.'},
 {r:'futuro', q:'Lewis Latimer ajudou a melhorar qual invenção no século XIX?', o:['A lâmpada elétrica','O automóvel','O avião','O rádio'],
  why:'Latimer patenteou em 1882 um jeito melhor de fabricar o filamento de carbono, que fez as lâmpadas durarem muito mais. Ele também desenhou a patente do telefone de Bell.'},
 {r:'futuro', q:'O engenheiro Mark Dean ajudou a criar qual máquina na IBM?', o:['O computador pessoal (PC)','O primeiro celular','O videogame portátil','A impressora 3D'],
  why:'Mark Dean é coinventor do IBM PC, de 1981, e tem patentes do computador original. Em 1999 liderou a equipe do primeiro chip de 1 gigahertz.'},
 {r:'futuro', q:'Lançado no Quênia em 2007, o M-Pesa ficou famoso por permitir...', o:['Mandar dinheiro pelo celular','Carros voadores','Internet via satélite','Robôs agricultores'],
  why:'Com o M-Pesa, milhões de pessoas sem conta em banco passaram a enviar e receber dinheiro por SMS. O Quênia virou referência mundial em pagamento pelo celular.'},
 {r:'futuro', q:'Sônia Guimarães fez história na ciência brasileira por ser...', o:['A primeira mulher negra doutora em física no Brasil','A primeira astronauta do Brasil','A inventora do Pix','A criadora da urna eletrônica'],
  why:'Sônia Guimarães concluiu o doutorado em física em 1989 e foi a primeira mulher negra a dar aulas no ITA. Ela incentiva meninas negras a seguirem a ciência.'}
];

// ------------- COMUNIDADE (construções) -------------
const BUILDINGS = [
 {id:'biblioteca', name:'Biblioteca Viva', ic:'📚', desc:'Guarda as memórias recuperadas.', bonus:'+5% de XP por nível', max:5, cost:[300,700,1400,2600,4500]},
 {id:'estudio', name:'Estúdio de Música', ic:'🎧', desc:'Onde Kwame e Eli ensaiam.', bonus:'+4% de energia inicial por nível', max:5, cost:[400,900,1700,3000,5000]},
 {id:'oficina', name:'Oficina Maker', ic:'🔧', desc:'Marcus e André criam e programam aqui.', bonus:'+4% de defesa da equipe por nível', max:5, cost:[400,900,1700,3000,5000]},
 {id:'quadra', name:'Quadra Comunitária', ic:'🏀', desc:'Treinos de Nia e Valentina.', bonus:'+4% de ataque da equipe por nível', max:5, cost:[400,900,1700,3000,5000]},
 {id:'mercado', name:'Mercado da Vila', ic:'🧺', desc:'Cooperativa organizada por Amara.', bonus:'+6% de Cauris por nível', max:5, cost:[350,800,1500,2800,4800]},
 {id:'cozinha', name:'Cozinha Coletiva', ic:'🍲', desc:'Chef Émile alimenta todo mundo.', bonus:'+4% de vida da equipe por nível', max:5, cost:[350,800,1500,2800,4800]},
 {id:'centro', name:'Centro Cultural', ic:'🎭', desc:'Festivais, rodas e exposições.', bonus:'+1 recompensa de missão diária por nível (Sementes)', max:3, cost:[1200,3000,6000]},
 {id:'baoba', name:'Baobá Ancestral', ic:'🌳', desc:'O coração da Vila. Cresce com o legado.', bonus:'+3% em todos os atributos por nível', max:5, cost:[1000,2500,5000,9000,15000]}
];

// ------------- EVENTOS SEMANAIS -------------
const EVENTS = [
 {name:'Festival dos Tambores', ic:'🥁', desc:'Personagens de Ritmo causam +25% de dano.', type:'Ritmo'},
 {name:'Feira de Inventores', ic:'⚙️', desc:'Personagens de Tech causam +25% de dano.', type:'Tech'},
 {name:'Campeonato da Vila', ic:'🏆', desc:'Personagens de Corpo causam +25% de dano.', type:'Corpo'},
 {name:'Semana do Conhecimento', ic:'📚', desc:'Personagens de Mente causam +25% de dano.', type:'Mente'},
 {name:'Noite dos Ancestrais', ic:'✨', desc:'Personagens de Espírito causam +25% de dano.', type:'Espírito'}
];

// ------------- MISSÕES DIÁRIAS -------------
const MISSION_POOL = [
 {id:'win3', text:'Vença 3 batalhas', stat:'wins', n:3, r:{cauris:150}},
 {id:'win5', text:'Vença 5 batalhas', stat:'wins', n:5, r:{cauris:250,sementes:5}},
 {id:'sp5', text:'Use 5 habilidades especiais', stat:'specials', n:5, r:{cauris:120}},
 {id:'ult2', text:'Use 2 supremas', stat:'ults', n:2, r:{cauris:150}},
 {id:'combo2', text:'Faça 2 combos de sinergia', stat:'combos', n:2, r:{cauris:180}},
 {id:'mini2', text:'Jogue 2 desafios rápidos', stat:'minis', n:2, r:{cauris:150}},
 {id:'quiz', text:'Acerte 5 perguntas no Quiz', stat:'quizRight', n:5, r:{sementes:5}},
 {id:'item1', text:'Encontre 1 colecionável', stat:'items', n:1, r:{cauris:200}},
 {id:'boss1', text:'Derrote 1 chefe', stat:'bosses', n:1, r:{sementes:10}},
 {id:'exp1', text:'Avance 3 salas na Expedição', stat:'rooms', n:3, r:{cauris:200}}
];

// ------------- BÊNÇÃOS DA EXPEDIÇÃO (roguelite) -------------
const BLESSINGS = [
 {id:'b_atk', name:'Força do Trovão', ic:'⚡', desc:'+15% de ataque na expedição.', mod:{atk:.15}},
 {id:'b_def', name:'Pele de Baobá', ic:'🌳', desc:'+20% de defesa na expedição.', mod:{def:.2}},
 {id:'b_heal', name:'Sopa da Avó', ic:'🍲', desc:'Cura 40% da equipe agora.', heal:.4},
 {id:'b_en', name:'Batida Constante', ic:'🥁', desc:'Começa cada luta com +40 de energia.', mod:{startEnergy:40}},
 {id:'b_crit', name:'Olho de Fotógrafa', ic:'📸', desc:'+15% de crítico.', mod:{crit:.15}},
 {id:'b_spd', name:'Vento do Sahel', ic:'🌬️', desc:'+15% de velocidade.', mod:{spd:.15}},
 {id:'b_life', name:'Ubuntu', ic:'🤝', desc:'+10% de roubo de vida.', mod:{lifesteal:.1}},
 {id:'b_gold', name:'Mercado Cheio', ic:'🐚', desc:'+50% de Cauris ao final.', mod:{coin:.5}},
 {id:'b_regen', name:'Chá de Ervas', ic:'🌿', desc:'Regenera 4% por turno.', mod:{regen:.04}}
];

// ------------- TÍTULOS / CORES -------------
const ACCENTS = [
 {id:'ouro',c:'#f5b82e',name:'Ouro',cost:0},{id:'vermelho',c:'#e8363d',name:'Vermelho Urucum',cost:30},
 {id:'verde',c:'#2fbf71',name:'Verde Floresta',cost:30},{id:'neon',c:'#00e5ff',name:'Ciano Neo-Axé',cost:60},
 {id:'magenta',c:'#ff2bd6',name:'Magenta Futuro',cost:60},{id:'terra',c:'#c8743a',name:'Terra Batida',cost:30}
];
