// ===================== DADOS DO JOGO =====================
const TYPES = {
  Ritmo:   {c:'#ff4d8d', ic:'♪', beats:'Mente'},
  Mente:   {c:'#5ec8ff', ic:'◈', beats:'Tech'},
  Tech:    {c:'#9d7bff', ic:'⚙', beats:'Corpo'},
  Corpo:   {c:'#ff8a2a', ic:'✊', beats:'Ritmo'},
  'Espírito': {c:'#f5c542', ic:'✦', beats:null}
};
const RAR = {
  'Comum':{c:'#b9a88f',n:1}, 'Rara':{c:'#3fbf7f',n:2}, 'Épica':{c:'#b06cff',n:3},
  'Lendária':{c:'#ffb520',n:4}, 'Mítica':{c:'#ff3d5a',n:5}
};

// efeitos: t = dmg | heal | buff | debuff | shield | stun | energy | cleanse | taunt
// alvo: one | all | team | self | ally(menor vida)
const CHARS = [
 {id:'protagonista', name:'Kayo', title:'Guardião do Legado', age:17, origin:'Vila Baobá, Salvador, Bahia (Brasil)', type:'Espírito', rar:'Mítica', role:'Equilibrado',
  hp:120, atk:22, def:12, spd:12,
  look:'Black power volumoso, moletom roxo com coroa dourada, mochila com o Livro Sankofa.',
  pers:'Curioso, teimoso e engraçado. Faz perguntas demais e escuta de verdade as respostas.',
  story:'Cresceu entre as estantes da Biblioteca Viva de Sankofa, onde a avó era guardiã. Quando a Névoa do Esquecimento começa a apagar os livros, o Livro Sankofa escolhe Kayo para viajar pelas memórias do mundo e trazê-las de volta.',
  basic:'Golpe de Cajado',
  sp:{name:'Chamado Sankofa', cd:3, desc:'Dano 170% e +25 de energia para toda a equipe.', fx:[{t:'dmg',m:1.7,tg:'one'},{t:'energy',v:25,tg:'team'}]},
  ult:{name:'Legado Vivo', desc:'Cura 35% da equipe e +30% de ataque por 3 turnos.', fx:[{t:'heal',v:.35,tg:'team'},{t:'buff',s:'atk',v:.3,d:3,tg:'team'}]},
  pas:{t:'energyGain',v:.15, desc:'Todos da equipe ganham 15% mais energia.'},
  lines:['Quem esquece de onde veio, se perde no caminho!','Sankofa: voltar e buscar.','Essa história ainda não acabou.'],
  anim:'Gira o cajado e desenha um Sankofa de luz dourada no ar.'},
 {id:'dj', name:'Kwame "Kwam" Mensah', title:'DJ', age:24, origin:'Acra, Gana', type:'Ritmo', rar:'Épica', role:'Suporte ofensivo',
  hp:95, atk:18, def:9, spd:15,
  look:'Fones enormes sempre no pescoço, jaqueta azul com colar de ouro, cabelo twist curto.',
  pers:'Carismático e acelerado. Resolve tudo com uma playlist.',
  story:'Começou tocando em casamentos no bairro de Jamestown, misturando highlife com eletrônica. Descobriu que certas batidas fazem a Névoa recuar e montou um set só para isso.',
  basic:'Scratch', sp:{name:'O Drop', cd:3, desc:'+30% de ataque para a equipe por 2 turnos e dano leve em todos.', fx:[{t:'buff',s:'atk',v:.3,d:2,tg:'team'},{t:'dmg',m:.6,tg:'all'}]},
  ult:{name:'Batida Infinita', desc:'Dano 130% em todos e +40 de energia para a equipe.', fx:[{t:'dmg',m:1.3,tg:'all'},{t:'energy',v:40,tg:'team'}]},
  pas:{t:'teamSpd',v:.1, desc:'Equipe com +10% de velocidade.'},
  lines:['Solta o som!','Essa faixa é pra minha avó em Acra.','Ninguém fica parado no meu turno.'], anim:'Levanta um disco holográfico que pulsa em ondas.'},
 {id:'atleta', name:'Nia Okonkwo', title:'Atleta', age:22, origin:'Lagos, Nigéria', type:'Corpo', rar:'Rara', role:'Golpes rápidos',
  hp:100, atk:24, def:8, spd:18,
  look:'Tranças longas presas alto, top esportivo preto e dourado, fita no pulso.',
  pers:'Competitiva, direta, ri alto quando perde e treina dobrado no dia seguinte.',
  story:'Velocista dos 200 metros que corre para bater o próprio recorde, não o dos outros. Ensina crianças do bairro a largar no bloco usando tampinhas como marcação.',
  basic:'Chute Veloz', sp:{name:'Largada Explosiva', cd:2, desc:'Três golpes de 70% em alvos aleatórios.', fx:[{t:'dmg',m:.7,tg:'rand'},{t:'dmg',m:.7,tg:'rand'},{t:'dmg',m:.7,tg:'rand'}]},
  ult:{name:'Recorde Mundial', desc:'Dano 300% em um alvo.', fx:[{t:'dmg',m:3,tg:'one'}]},
  pas:{t:'crit',v:.2, desc:'20% de chance de crítico.'},
  lines:['Pisca e perdeu!','Linha de chegada é ali.','Mais um tiro!'], anim:'Entra em posição de largada com rastro de luz laranja.'},
 {id:'engenheiro', name:'André Cruz', title:'Engenheiro de Software', age:38, origin:'Rio de Janeiro, Brasil', type:'Tech', rar:'Lendária', role:'Defensor',
  hp:118, atk:17, def:15, spd:11,
  look:'Barba curta bem desenhada, blazer cinza sobre camisa preta, tablet holográfico azul sempre aceso nas mãos.',
  pers:'Calmo, analítico e direto. Pensa em sistemas, fala em soluções e só comemora depois que tudo passa nos testes.',
  story:'Engenheiro de software que cresceu vendo o Rio do alto do morro. Criou o sistema que digitaliza e protege o acervo da Biblioteca Viva, e é por isso que a Névoa não consegue apagar o que ele já salvou. Acredita que conhecimento também é poder, e que código bom é aquele que cuida das pessoas.',
  basic:'Pulso de Código', sp:{name:'Firewall', cd:3, desc:'Escudo de 25% da vida máxima para a equipe.', fx:[{t:'shield',v:.25,tg:'team'}]},
  ult:{name:'Deploy em Produção', desc:'Escudo de 40% na equipe e dano 100% em todos.', fx:[{t:'shield',v:.4,tg:'team'},{t:'dmg',m:1,tg:'all'}]},
  pas:{t:'def',v:.15, desc:'+15% de defesa própria.'},
  lines:['Compilado e testado.','Conhecimento também é poder.','Deixa que eu faço o deploy.'], anim:'Toca no tablet e uma cúpula de código hexagonal azul envolve a equipe.'},
 {id:'historiadora', name:'Makeda Tesfaye', title:'Historiadora', age:34, origin:'Adis Abeba, Etiópia', type:'Mente', rar:'Épica', role:'Enfraquecedora',
  hp:95, atk:19, def:10, spd:13,
  look:'Turbante estampado laranja e azul, argolas douradas, bolsa de couro cheia de mapas.',
  pers:'Paciente, irônica, conta uma história para cada pergunta.',
  story:'Especialista em manuscritos antigos em ge\'ez, a antiga língua litúrgica da Etiópia. Sabe que a Névoa sempre ataca primeiro o que ninguém anotou.',
  basic:'Pergaminho', sp:{name:'Fonte Primária', cd:3, desc:'Reduz defesa de todos os inimigos em 35% por 3 turnos.', fx:[{t:'debuff',s:'def',v:.35,d:3,tg:'all'}]},
  ult:{name:'Arquivo Revelado', desc:'Dano 180% em todos e revela fraquezas (+20% de dano recebido).', fx:[{t:'dmg',m:1.8,tg:'all'},{t:'debuff',s:'vuln',v:.2,d:3,tg:'all'}]},
  pas:{t:'drop',v:.1, desc:'+10% de chance de encontrar colecionáveis.'},
  lines:['Todo documento tem uma voz.','Isso já aconteceu antes. E venceram.','Anota isso!'], anim:'Abre um mapa que se transforma em linhas de luz.'},
 {id:'artista', name:'Zuri Achieng', title:'Artista', age:26, origin:'Nairóbi, Quênia', type:'Espírito', rar:'Épica', role:'Dano em área',
  hp:95, atk:21, def:9, spd:13,
  look:'Cabelo crespo solto, jardineira branca manchada de tinta colorida, latas de spray no cinto.',
  pers:'Sonhadora e intensa, desenha em qualquer superfície (inclusive em você).',
  story:'Pinta murais em matatus, os micro-ônibus decorados de Nairóbi. Suas cores dão forma a memórias que a Névoa tentou apagar.',
  basic:'Pincelada', sp:{name:'Mural Vivo', cd:3, desc:'Dano 110% em todos com 25% de chance de atordoar.', fx:[{t:'dmg',m:1.1,tg:'all'},{t:'stun',p:.25,tg:'all'}]},
  ult:{name:'Obra-Prima', desc:'Dano 220% em todos.', fx:[{t:'dmg',m:2.2,tg:'all'}]},
  pas:{t:'aoeBonus',v:.15, desc:'+15% de dano em ataques em área.'},
  lines:['Cor é resistência!','Parede vazia é convite.','Ficou lindo, né?'], anim:'Arremessa tinta que forma padrões geométricos.'},
 {id:'inventor', name:'Marcus Bell', title:'Inventor', age:31, origin:'Detroit, EUA', type:'Tech', rar:'Épica', role:'Dano contínuo',
  hp:105, atk:21, def:11, spd:11,
  look:'Óculos de solda na testa, luva mecânica azul, colete cheio de ferramentas.',
  pers:'Barulhento, otimista, conversa com as próprias máquinas.',
  story:'Neto de operários da indústria automobilística, transforma sucata em robôs úteis. Tem uma oficina aberta onde qualquer criança pode desmontar algo.',
  basic:'Chave Inglesa', sp:{name:'Drone Faísca', cd:2, desc:'Dano 150% e reduz ataque do alvo em 20%.', fx:[{t:'dmg',m:1.5,tg:'one'},{t:'debuff',s:'atk',v:.2,d:2,tg:'one'}]},
  ult:{name:'Protótipo Final', desc:'Dano 260% em um alvo e 80% nos demais.', fx:[{t:'dmg',m:2.6,tg:'one'},{t:'dmg',m:.8,tg:'others'}]},
  pas:{t:'crit',v:.1, desc:'10% de crítico; críticos dão +10 de energia.'},
  lines:['Funcionou! Eu acho.','Detroit constrói.','Mais uma engrenagem...'], anim:'Solta um drone que faísca em azul.'},
 {id:'capoeirista', name:'Luana "Ginga" Santos', title:'Capoeirista', age:23, origin:'Salvador, Bahia (Brasil)', type:'Corpo', rar:'Rara', role:'Esquiva e contra-ataque',
  hp:105, atk:21, def:10, spd:16,
  look:'Faixa amarela na cabeça, cabelo crespo preso, abadá branco, pés descalços.',
  pers:'Brincalhona, esperta, sempre com um sorriso antes de um golpe.',
  story:'Treina desde os seis anos numa roda no Pelourinho. Para ela, capoeira é jogo, música, conversa e memória ao mesmo tempo.',
  basic:'Meia-lua', sp:{name:'Au e Martelo', cd:2, desc:'Dano 160% e +40% de esquiva por 2 turnos.', fx:[{t:'dmg',m:1.6,tg:'one'},{t:'buff',s:'dodge',v:.4,d:2,tg:'self'}]},
  ult:{name:'Roda Completa', desc:'Dano 150% em todos e esquiva total por 1 turno.', fx:[{t:'dmg',m:1.5,tg:'all'},{t:'buff',s:'dodge',v:1,d:1,tg:'self'}]},
  pas:{t:'counter',v:.3, desc:'30% de chance de contra-atacar ao ser atingida.'},
  lines:['Iê, vamos embora!','Ginga não é fuga, é estratégia.','Quem joga, aprende.'], anim:'Faz um aú no lugar e ginga ao ritmo do berimbau.'},
 {id:'empreendedora', name:'Amara Diallo', title:'Empreendedora', age:32, origin:'Dakar, Senegal', type:'Mente', rar:'Rara', role:'Economia',
  hp:95, atk:17, def:10, spd:12,
  look:'Blazer preto elegante, cabelo longo liso, brincos de ouro, sempre com um café.',
  pers:'Estratégica, persuasiva e generosa com quem está começando.',
  story:'Fundou uma cooperativa de tecelãs que exporta tecidos para três continentes. Sua regra: todo lucro volta, em parte, para a comunidade.',
  basic:'Contrato Relâmpago', sp:{name:'Investimento', cd:3, desc:'+25% de ataque e +20 de energia para um aliado.', fx:[{t:'buff',s:'atk',v:.25,d:3,tg:'ally'},{t:'energy',v:20,tg:'ally'}]},
  ult:{name:'Rodada de Sucesso', desc:'Dano 150% em todos e +25% de Cauris no fim da batalha.', fx:[{t:'dmg',m:1.5,tg:'all'},{t:'coinBoost',v:.25}]},
  pas:{t:'coin',v:.2, desc:'+20% de Cauris ganhos.'},
  lines:['Isso é um bom negócio para todos.','Crescemos juntos.','Tempo também é recurso.'], anim:'Toca num holograma de gráfico que sobe.'},
 {id:'pesquisador', name:'Thabo Nkosi', title:'Pesquisador', age:28, origin:'Joanesburgo, África do Sul', type:'Mente', rar:'Rara', role:'Críticos',
  hp:100, atk:20, def:10, spd:13,
  look:'Óculos redondos, barba cheia, moletom bege com mochila de campo.',
  pers:'Observador e tímido, só fica falante quando acha uma pista.',
  story:'Arqueólogo que estuda os sítios de Mapungubwe e do Grande Zimbábue. Carrega um caderno onde desenha cada pedra antes de tocá-la.',
  basic:'Martelo Geológico', sp:{name:'Análise de Campo', cd:2, desc:'Dano 140% que sempre acerta crítico em alvos enfraquecidos.', fx:[{t:'dmg',m:1.4,tg:'one',critDebuffed:true}]},
  ult:{name:'Grande Descoberta', desc:'Dano 250% e garante um colecionável extra se vencer.', fx:[{t:'dmg',m:2.5,tg:'one'},{t:'lootBoost'}]},
  pas:{t:'drop',v:.15, desc:'+15% de chance de encontrar colecionáveis.'},
  lines:['Espera... olha isso!','Toda pedra tem data.','Evidência primeiro.'], anim:'Levanta um artefato que brilha.'},
 {id:'lider', name:'Kofi Boateng', title:'Líder Comunitário', age:52, origin:'Kumasi, Gana', type:'Espírito', rar:'Lendária', role:'Líder',
  hp:125, atk:17, def:13, spd:10,
  look:'Dreadlocks longos, faixa azul, camisa de padrões kente, muitos colares de contas.',
  pers:'Sábio, bem-humorado, conhece o nome de todo mundo e da mãe de todo mundo.',
  story:'Mentor de Kayo e fundador da Vila Baobá. Viajou o mundo organizando cooperativas. Diz que comunidade é um verbo.',
  basic:'Bastão do Conselho', sp:{name:'Ubuntu', cd:3, desc:'Cura 25% da equipe e remove efeitos negativos.', fx:[{t:'heal',v:.25,tg:'team'},{t:'cleanse',tg:'team'}]},
  ult:{name:'Conselho dos Anciões', desc:'+30% de ataque e defesa para a equipe por 3 turnos.', fx:[{t:'buff',s:'atk',v:.3,d:3,tg:'team'},{t:'buff',s:'def',v:.3,d:3,tg:'team'}]},
  pas:{t:'teamAll',v:.08, desc:'Equipe com +8% em todos os atributos.'},
  lines:['Eu sou porque nós somos.','Ninguém fica pra trás.','Paciência, jovem.'], anim:'Bate o bastão no chão e anéis de luz se espalham.'},
 {id:'medica', name:'Dra. Aline Ferreira', title:'Médica', age:35, origin:'Belo Horizonte, Brasil', type:'Mente', rar:'Épica', role:'Curandeira',
  hp:100, atk:14, def:11, spd:12,
  look:'Tranças presas, óculos finos, jaleco branco com estetoscópio e crachá.',
  pers:'Serena sob pressão, exigente com a saúde dos outros e esquecida com a própria.',
  story:'Médica de família em uma unidade básica de saúde. Criou um programa de saúde nas escolas que virou referência.',
  basic:'Diagnóstico', sp:{name:'Triagem', cd:2, desc:'Cura 40% do aliado mais ferido.', fx:[{t:'heal',v:.4,tg:'ally'}]},
  ult:{name:'Plantão Heroico', desc:'Cura 50% da equipe e revive aliados com 30% de vida.', fx:[{t:'revive',v:.3},{t:'heal',v:.5,tg:'team'}]},
  pas:{t:'healBonus',v:.2, desc:'+20% de cura.'},
  lines:['Respira. Vai ficar tudo bem.','Hidratação, gente!','Sinais vitais estáveis.'], anim:'Toca o estetoscópio e uma cruz verde brilha.'},
 {id:'policial', name:'Tenente Caio Rocha', title:'Guarda Protetor', age:38, origin:'Recife, Brasil', type:'Corpo', rar:'Rara', role:'Tanque',
  hp:150, atk:15, def:18, spd:8,
  look:'Uniforme tático preto, ombros largos, corte baixo, postura firme.',
  pers:'Protetor e sério, mas derrete completamente perto de cachorros.',
  story:'Trabalha com mediação de conflitos e segurança comunitária. Acredita que proteger é, antes de tudo, conhecer as pessoas do bairro.',
  basic:'Empurrão de Escudo', sp:{name:'Linha de Frente', cd:3, desc:'Provoca os inimigos por 2 turnos e ganha 40% de defesa.', fx:[{t:'taunt',d:2},{t:'buff',s:'def',v:.4,d:2,tg:'self'}]},
  ult:{name:'Barreira Total', desc:'Escudo de 50% em toda a equipe.', fx:[{t:'shield',v:.5,tg:'team'}]},
  pas:{t:'thorns',v:.2, desc:'Devolve 20% do dano recebido.'},
  lines:['Fiquem atrás de mim.','Ninguém passa.','Tá tudo sob controle.'], anim:'Crava o escudo no chão.'},
 {id:'musico', name:'Eli Fontenot', title:'Músico', age:45, origin:'Nova Orleans, EUA', type:'Ritmo', rar:'Épica', role:'Suporte',
  hp:105, atk:17, def:11, spd:11,
  look:'Chapéu de aba larga, violão nas costas, barba grisalha, colete de couro.',
  pers:'Tranquilo e melancólico, fala devagar e toca rápido.',
  story:'Toca blues nas varandas do bairro de Tremé desde menino. Diz que o blues é a arte de transformar dor em algo bonito para compartilhar.',
  basic:'Acorde', sp:{name:'Blues da Madrugada', cd:3, desc:'Cura 20% da equipe e reduz ataque inimigo em 20%.', fx:[{t:'heal',v:.2,tg:'team'},{t:'debuff',s:'atk',v:.2,d:2,tg:'all'}]},
  ult:{name:'Improviso de Jazz', desc:'Dano 160% em todos e cura 20% da equipe.', fx:[{t:'dmg',m:1.6,tg:'all'},{t:'heal',v:.2,tg:'team'}]},
  pas:{t:'regen',v:.03, desc:'Equipe regenera 3% de vida por turno.'},
  lines:['Deixa a guitarra falar.','Todo mundo tem um blues.','Mais um compasso...'], anim:'Dedilha o violão e notas azuis flutuam.'},
 {id:'dancarina', name:'Yamilé Castillo', title:'Dançarina', age:24, origin:'Havana, Cuba', type:'Ritmo', rar:'Rara', role:'Velocidade',
  hp:90, atk:20, def:8, spd:19,
  look:'Cabelo crespo gigante com faixa dourada, top roxo, pulseiras que tilintam.',
  pers:'Expansiva, dramática e muito leal.',
  story:'Dançarina de rumba e dança contemporânea. Ensina que cada passo carrega um pedaço de história que veio pelo Atlântico.',
  basic:'Giro', sp:{name:'Rumba Relâmpago', cd:2, desc:'Dano 120% em todos e +20% de velocidade na equipe.', fx:[{t:'dmg',m:1.2,tg:'all'},{t:'buff',s:'spd',v:.2,d:2,tg:'team'}]},
  ult:{name:'Coreografia Final', desc:'Dano 200% em todos.', fx:[{t:'dmg',m:2,tg:'all'}]},
  pas:{t:'dodge',v:.2, desc:'20% de esquiva.'},
  lines:['Sente o compasso!','Um, dois, três... agora!','A pista é minha.'], anim:'Gira e deixa um rastro dourado.'},
 {id:'chef', name:'Chef Émile Laurent', title:'Chef', age:40, origin:'Porto Príncipe, Haiti', type:'Espírito', rar:'Rara', role:'Suporte',
  hp:120, atk:15, def:13, spd:10,
  look:'Dólmã branca impecável, chapéu de chef alto, braços cruzados e sorriso de canto.',
  pers:'Perfeccionista e acolhedor: vai criticar seu tempero e depois te dar o prato inteiro.',
  story:'Cozinha a soup joumou, sopa que os haitianos tomam todo 1º de janeiro para celebrar a independência de 1804. Acredita que comida guarda memória melhor que livro.',
  basic:'Colherada', sp:{name:'Soup Joumou', cd:3, desc:'Cura 30% e +20% de defesa na equipe.', fx:[{t:'heal',v:.3,tg:'team'},{t:'buff',s:'def',v:.2,d:3,tg:'team'}]},
  ult:{name:'Banquete da Liberdade', desc:'Cura 45% da equipe e +50 de energia para todos.', fx:[{t:'heal',v:.45,tg:'team'},{t:'energy',v:50,tg:'team'}]},
  pas:{t:'healBonus',v:.1, desc:'+10% de cura.'},
  lines:['Com tempero de casa!','Comida é memória.','Senta, come, depois a gente luta.'], anim:'Levanta uma panela fumegante dourada.'},
 {id:'fotografa', name:'Imani Clarke', title:'Fotógrafa', age:27, origin:'Kingston, Jamaica', type:'Mente', rar:'Rara', role:'Controle',
  hp:95, atk:18, def:9, spd:14,
  look:'Cabelo crespo com faixa estampada, câmera analógica pendurada, colete de bolsos.',
  pers:'Silenciosa e atenta, percebe o que todo mundo deixa passar.',
  story:'Documenta festas de rua, sound systems e artesãos da ilha. Seu projeto é um arquivo fotográfico que qualquer pessoa pode acessar.',
  basic:'Flash', sp:{name:'Clique Decisivo', cd:3, desc:'Dano 130% e 60% de chance de atordoar.', fx:[{t:'dmg',m:1.3,tg:'one'},{t:'stun',p:.6,tg:'one'}]},
  ult:{name:'Exposição Total', desc:'Atordoa todos os inimigos (70%) e causa dano 120%.', fx:[{t:'dmg',m:1.2,tg:'all'},{t:'stun',p:.7,tg:'all'}]},
  pas:{t:'drop',v:.1, desc:'+10% de chance de colecionáveis.'},
  lines:['Não se mexe... pronto!','Essa foto vai pro arquivo.','A luz tá perfeita.'], anim:'Dispara um flash que congela o tempo.'},
 {id:'astronauta', name:'Cmdte. Ayana Okafor', title:'Astronauta', age:33, origin:'Neo-Axé (família de Enugu, Nigéria)', type:'Tech', rar:'Lendária', role:'Dano massivo',
  hp:105, atk:23, def:12, spd:12,
  look:'Traje espacial branco com capacete de viseira azul, patch de estrela dourada.',
  pers:'Disciplinada, calorosa, sempre olha para o céu antes de decidir.',
  story:'Primeira comandante da estação orbital de Neo-Axé. Estuda como povos antigos usavam as estrelas para navegar e plantar.',
  basic:'Propulsor', sp:{name:'Gravidade Zero', cd:3, desc:'Dano 140% em todos e reduz velocidade inimiga.', fx:[{t:'dmg',m:1.4,tg:'all'},{t:'debuff',s:'spd',v:.3,d:2,tg:'all'}]},
  ult:{name:'Chuva de Estrelas', desc:'Dano 280% em todos.', fx:[{t:'dmg',m:2.8,tg:'all'}]},
  pas:{t:'ultBonus',v:.2, desc:'+20% de dano na suprema.'},
  lines:['Contagem regressiva: três, dois...','O céu é só o começo.','Houston? Não, Neo-Axé.'], anim:'Flutua e a viseira reflete galáxias.'},
 {id:'guerreiro', name:'Sipho Dlamini', title:'Mestre dos Bastões', age:30, origin:'Durban, África do Sul', type:'Corpo', rar:'Épica', role:'Dano pesado',
  hp:135, atk:25, def:13, spd:10,
  look:'Pintura facial vermelha de palco, colares de contas, ombros largos, bastões cruzados nas costas.',
  pers:'Intenso nos treinos, brincalhão fora deles, canta alto no chuveiro.',
  story:'Campeão da luta com bastões, tradição nguni de habilidade e respeito, e ator de teatro. Usa a pintura em apresentações para contar histórias do seu povo.',
  basic:'Bastão Duplo', sp:{name:'Guarda Nguni', cd:3, desc:'Dano 200% e ganha 30% de defesa.', fx:[{t:'dmg',m:2,tg:'one'},{t:'buff',s:'def',v:.3,d:2,tg:'self'}]},
  ult:{name:'Trovão dos Bastões', desc:'Dano 320% em um alvo.', fx:[{t:'dmg',m:3.2,tg:'one'}]},
  pas:{t:'lifesteal',v:.15, desc:'Recupera 15% do dano causado.'},
  lines:['Respeito primeiro. Depois, o golpe.','Sente a força!','Mais um round!'], anim:'Gira os bastões em X.'},
 {id:'cantora', name:'Fatou Keita', title:'Cantora', age:29, origin:'Bamako, Mali', type:'Ritmo', rar:'Lendária', role:'Suporte ofensivo',
  hp:100, atk:20, def:10, spd:13,
  look:'Turbante alto multicolorido, joias douradas em camadas, voz que enche o salão.',
  pers:'Elegante, espirituosa, discorda com uma melodia.',
  story:'Neta de griots, os guardiões da palavra e da música da África Ocidental. Canta genealogias inteiras de cor e agora canta para lembrar ao mundo quem ele é.',
  basic:'Nota Aguda', sp:{name:'Canto Griot', cd:3, desc:'Dano 120% em todos e cura 15% da equipe.', fx:[{t:'dmg',m:1.2,tg:'all'},{t:'heal',v:.15,tg:'team'}]},
  ult:{name:'Voz dos Ancestrais', desc:'Dano 200% em todos e +30 de energia para a equipe.', fx:[{t:'dmg',m:2,tg:'all'},{t:'energy',v:30,tg:'team'}]},
  pas:{t:'teamAtk',v:.1, desc:'Equipe com +10% de ataque.'},
  lines:['Escuta a história do seu nome.','Minha voz carrega séculos.','Canta comigo!'], anim:'Abre os braços e ondas douradas de som saem.'},
 {id:'cientista', name:'Dr. Samuel Adjei', title:'Cientista', age:37, origin:'Toronto, Canadá (pais de Gana)', type:'Tech', rar:'Rara', role:'Enfraquecedor',
  hp:100, atk:18, def:11, spd:12,
  look:'Óculos grossos, jaleco com camisa azul, tablet de dados sempre aceso.',
  pers:'Entusiasta, fala rápido quando empolgado e explica tudo com analogias de comida.',
  story:'Bioquímico que pesquisa plantas medicinais tradicionais junto com as comunidades que as conhecem há séculos, dando crédito a elas nos artigos.',
  basic:'Amostra', sp:{name:'Hipótese', cd:2, desc:'Reduz defesa do alvo em 40% e causa 120% de dano.', fx:[{t:'debuff',s:'def',v:.4,d:3,tg:'one'},{t:'dmg',m:1.2,tg:'one'}]},
  ult:{name:'Revisão por Pares', desc:'Dano 200% em todos que estiverem enfraquecidos, 100% nos outros.', fx:[{t:'dmg',m:1,tg:'all',bonusDebuffed:1}]},
  pas:{t:'debuffDur',v:1, desc:'Efeitos negativos duram +1 turno.'},
  lines:['Dados não mentem.','Hipótese confirmada!','Interessante...'], anim:'Toca no tablet e fórmulas orbitam.'},
 {id:'esportista', name:'Valentina Mosquera', title:'Esportista', age:20, origin:'Quibdó, Colômbia', type:'Corpo', rar:'Rara', role:'Velocidade',
  hp:100, atk:21, def:9, spd:17,
  look:'Tranças presas em coque alto, roupa de treino preta, tablet de estatísticas.',
  pers:'Focada, estrategista, analisa os vídeos dos próprios jogos toda noite.',
  story:'Atacante de futebol da região do Pacífico colombiano, de maioria afro-colombiana. Estuda análise de dados para virar técnica um dia.',
  basic:'Chute', sp:{name:'Contra-Ataque', cd:2, desc:'Dano 150% e age de novo mais rápido (+30 de energia).', fx:[{t:'dmg',m:1.5,tg:'one'},{t:'energy',v:30,tg:'self'}]},
  ult:{name:'Golaço', desc:'Dano 270% em um alvo com crítico garantido.', fx:[{t:'dmg',m:2.7,tg:'one',crit:true}]},
  pas:{t:'crit',v:.15, desc:'15% de crítico.'},
  lines:['Bola no ângulo!','Joga pro time!','Analisei seu padrão.'], anim:'Faz embaixadinha com uma bola de luz.'}
];
const CH = Object.fromEntries(CHARS.map(c=>[c.id,c]));

const SYNERGIES = [
 {a:'dj',b:'dancarina',name:'Bônus de Ritmo',desc:'Equipe +15% de velocidade.',mod:{spd:.15}},
 {a:'engenheiro',b:'inventor',name:'Tecnologia Avançada',desc:'Escudos +30%.',mod:{shield:.3}},
 {a:'atleta',b:'capoeirista',name:'Combo Físico',desc:'Equipe +12% de ataque.',mod:{atk:.12}},
 {a:'historiadora',b:'pesquisador',name:'Descoberta de Artefatos',desc:'+25% de chance de colecionáveis.',mod:{drop:.25}},
 {a:'musico',b:'cantora',name:'Dueto',desc:'Curas +25%.',mod:{heal:.25}},
 {a:'medica',b:'chef',name:'Corpo e Alma',desc:'Equipe regenera 3% por turno.',mod:{regen:.03}},
 {a:'astronauta',b:'cientista',name:'Missão Orbital',desc:'Supremas +20% de dano.',mod:{ult:.2}},
 {a:'lider',b:'empreendedora',name:'Economia Solidária',desc:'+25% de Cauris.',mod:{coin:.25}},
 {a:'fotografa',b:'artista',name:'Galeria Viva',desc:'+15% de chance de atordoar.',mod:{stun:.15}},
 {a:'policial',b:'guerreiro',name:'Muralha',desc:'Equipe +20% de defesa.',mod:{def:.2}},
 {a:'protagonista',b:'lider',name:'Sankofa',desc:'Equipe ganha +15% de energia.',mod:{energy:.15}},
 {a:'esportista',b:'atleta',name:'Pódio',desc:'+10% de crítico.',mod:{crit:.1}}
];

// ---------------- REGIÕES ----------------
const REGIONS = [
 {id:'brasil', name:'Brasil', sub:'Salvador & Rio', ch:1, lvl:1, c1:'#1f8a4c', c2:'#ffd23f', sky:['#ff9a3c','#ff4f6d','#3a1c5c'], genre:'samba', scene:'brasil',
  desc:'Rodas de capoeira no Pelourinho, blocos afro e o som do surdo ecoando pelas ladeiras.',
  chars:['capoeirista','engenheiro','medica','policial'], unlock:'medica',
  enemies:['sombraviva','lucifer','necro'], boss:'reicinza'},
 {id:'ocidental', name:'África Ocidental', sub:'Tombuctu & Acra', ch:2, lvl:4, c1:'#c8741a', c2:'#f5c542', sky:['#ffcf6b','#e0782a','#5b2a14'], genre:'afrobeat', scene:'ocidental',
  desc:'Bibliotecas de manuscritos, tecidos kente e o legado dos grandes impérios do Sahel.',
  chars:['dj','cantora','empreendedora','lider'], unlock:'cantora',
  enemies:['kadu','brasa','necro'], boss:'ladrao'},
 {id:'caribe', name:'Caribe', sub:'Kingston, Havana & Porto Príncipe', ch:2, lvl:7, c1:'#00a5a8', c2:'#ff5e5b', sky:['#7ee8fa','#2f9fd6','#123a6b'], genre:'reggae', scene:'caribe',
  desc:'Sound systems, rumba, steel pan e a primeira república negra independente das Américas.',
  chars:['fotografa','dancarina','chef'], unlock:'chef',
  enemies:['lucifer','azira','sangria'], boss:'furacao'},
 {id:'eua', name:'Estados Unidos', sub:'Nova Orleans, Detroit & Bronx', ch:3, lvl:10, c1:'#3d5afe', c2:'#ff3d7f', sky:['#6a5acd','#2b2266','#0c0a24'], genre:'jazz', scene:'eua',
  desc:'O nascimento do jazz, do blues, da soul e do hip-hop, e a genialidade de inventores e inventoras.',
  chars:['musico','inventor'], unlock:'musico',
  enemies:['glacio','brasa','sombraviva'], boss:'disco'},
 {id:'austral', name:'África Austral', sub:'Grande Zimbábue & Joanesburgo', ch:4, lvl:13, c1:'#8b5e34', c2:'#4fd1a5', sky:['#ffd9a0','#c9864a','#3b2412'], genre:'amapiano', scene:'austral',
  desc:'Cidades de pedra sem argamassa, ubuntu e as batidas graves do amapiano.',
  chars:['pesquisador','guerreiro'], unlock:'pesquisador',
  enemies:['brasa','kadu','ferrugem'], boss:'muralha'},
 {id:'latina', name:'América Latina', sub:'Palenque & Pacífico colombiano', ch:5, lvl:16, c1:'#2e7d32', c2:'#ffca28', sky:['#b2f7a1','#3fa35b','#0f3a22'], genre:'cumbia', scene:'latina',
  desc:'San Basilio de Palenque, o primeiro povoado livre das Américas, e a música do litoral do Pacífico.',
  chars:['esportista'], unlock:'esportista',
  enemies:['ferrugem','sangria','azira'], boss:'serpente'},
 {id:'oriental', name:'África Oriental', sub:'Aksum, Lalibela & Nairóbi', ch:6, lvl:19, c1:'#b23a48', c2:'#fcb07e', sky:['#ffe0b2','#f28c52','#6b2130'], genre:'ethio', scene:'oriental',
  desc:'Obeliscos de Aksum, igrejas esculpidas na rocha, maratonistas e a arte urbana de Nairóbi.',
  chars:['historiadora','artista'], unlock:'artista',
  enemies:['kadu','necro','azira'], boss:'colosso'},
 {id:'futuro', name:'Neo-Axé', sub:'Cidade afrofuturista', ch:7, lvl:22, c1:'#00e5ff', c2:'#ff2bd6', sky:['#2b0a4a','#140833','#04020f'], genre:'afrofuturo', scene:'futuro',
  desc:'Torres de metal com padrões geométricos, mercados holográficos e a universidade que guarda o futuro.',
  chars:['astronauta','cientista'], unlock:'astronauta',
  enemies:['glacio','ferrugem','sombraviva'], boss:'apagao'}
];
const RG = Object.fromEntries(REGIONS.map(r=>[r.id,r]));

// ---------------- INIMIGOS ----------------
// A Névoa do Esquecimento assume formas. Derrotá-las liberta memórias.
const ENEMIES = {
 sombraviva:{name:'Sombra Viva', power:'Manipulação Mental', img:'v_sombraviva', type:'Mente', hp:70, atk:15, def:7, spd:12, style:'debuffAtk', desc:'Encapuzado que sussurra dúvidas na mente dos heróis e enfraquece seus golpes.'},
 necro:     {name:'Necro', power:'Energia Negativa', img:'v_necro', type:'Espírito', hp:78, atk:13, def:8, spd:9, style:'aoe', desc:'Espalha energia negativa que atinge a equipe inteira de uma vez.'},
 sangria:   {name:'Sangria', power:'Vampirismo', img:'v_sangria', type:'Corpo', hp:72, atk:16, def:7, spd:12, style:'lifesteal', desc:'Rouba a vitalidade dos adversários para se curar.'},
 ferrugem:  {name:'Ferrugem', power:'Destruição Ambiental', img:'v_ferrugem', type:'Tech', hp:88, atk:14, def:10, spd:8, style:'corrode', desc:'Máquina tóxica que corrói a defesa de todos ao redor.'},
 lucifer:   {name:'Lúcifer', power:'Vício', img:'v_lucifer', type:'Ritmo', hp:66, atk:17, def:6, spd:14, style:'drain', desc:'Hipnotiza com luz e drena a energia de quem olha nos olhos dela.'},
 glacio:    {name:'Glácio', power:'Infiltração', img:'v_glacio', type:'Tech', hp:70, atk:18, def:8, spd:16, style:'nuke', dodge:.15, desc:'Infiltrador rápido e difícil de acertar. Seu golpe gelado é devastador.'},
 kadu:      {name:'Kadu', power:'Rituais Sombrios', img:'v_kadu', type:'Espírito', hp:76, atk:15, def:8, spd:11, style:'debuffDef', desc:'Usa rituais sombrios para deixar os heróis vulneráveis.'},
 azira:     {name:'Azira', power:'Domínio Espiritual', img:'v_azira', type:'Espírito', hp:72, atk:13, def:8, spd:11, style:'healAlly', desc:'Controla espíritos para curar e proteger os aliados vilões.'},
 brasa:     {name:'Brasa Negra', power:'Guerra', img:'v_brasa', type:'Corpo', hp:112, atk:16, def:13, spd:7, style:'tank', desc:'Guerreiro brutal que aguenta muito dano e bate forte.'}
};
const BOSSES = {
 reicinza:{name:'Zara', power:'Caos', img:'v_zara', type:'Ritmo', hp:470, atk:22, def:12, spd:11, region:'brasil', color:'#e8363d',
   intro:'Carnaval? Batuque? Eu prefiro o caos. E o caos não tem ritmo!', skill:'Tempestade do Caos', desc:'Quer cancelar o carnaval e transformar as rodas de Salvador em confusão.'},
 ladrao:{name:'Kemet', power:'Dominação Cultural', img:'v_kemet', type:'Mente', hp:520, atk:24, def:13, spd:11, region:'ocidental', color:'#f5a623',
   intro:'Toda cultura que eu não controlo, eu apago. Tombuctu será a primeira.', skill:'Decreto de Ouro', desc:'Mascarado que quer controlar e reescrever os manuscritos de Tombuctu.'},
 furacao:{name:'Malika', power:'Terror Psicológico', img:'v_malika', type:'Mente', hp:600, atk:24, def:12, spd:14, region:'caribe', color:'#c9c9d9',
   intro:'Medo é mais forte que memória. As ilhas vão esquecer de tanto medo.', skill:'Pesadelo', desc:'Espalha medo pelas ilhas até as pessoas pararem de cantar e festejar.'},
 disco:{name:'Vértice', power:'Controle Tecnológico', img:'v_vertice', type:'Tech', hp:700, atk:27, def:14, spd:12, region:'eua', color:'#3fa9ff',
   intro:'Coloquei toda a música deste país num loop. Controle total, sem improviso.', skill:'Loop Infinito', desc:'Hacker que prende o jazz, o blues e o hip-hop num loop sem criatividade.'},
 muralha:{name:'Colôsso', power:'Força Bruta', img:'v_colosso', type:'Corpo', hp:820, atk:27, def:16, spd:7, region:'austral', color:'#d8342c',
   intro:'Pedra se quebra. Nomes se quebram. Eu quebro tudo.', skill:'Desmoronamento', desc:'Brutamontes mascarado que tenta derrubar as muralhas do Grande Zimbábue.'},
 serpente:{name:'Toxina', power:'Contaminação', img:'v_toxina', type:'Tech', hp:880, atk:30, def:15, spd:15, region:'latina', color:'#39ff6a',
   intro:'Um pouco de veneno nas trilhas e ninguém mais acha o caminho de volta.', skill:'Nuvem Tóxica', desc:'Contamina as trilhas da floresta que levavam aos palenques.'},
 colosso:{name:'Senhor das Areias', power:'Ilusão', img:'v_areias', type:'Espírito', hp:1000, atk:31, def:17, spd:10, region:'oriental', color:'#e7d3a8',
   intro:'Obeliscos? Reinos? Tudo miragem. Deixe a areia cobrir.', skill:'Miragem', desc:'Ilusionista elegante que quer convencer o mundo de que Aksum e Lalibela nunca existiram.'},
 apagao:{name:'Vulcano', power:'Destruição Tecnológica', img:'v_vulcano', type:'Tech', hp:1150, atk:34, def:18, spd:14, region:'futuro', color:'#ff4d4d',
   intro:'Corrompi a IA do arquivo. Formatar Neo-Axé vai ser divertido.', skill:'Formatar Tudo', desc:'Corrompeu a IA que protege o arquivo de Neo-Axé para deletar tudo.'},
 esquecimento:{name:'Obsidian', power:'Destruição Total', img:'v_obsidian', type:'Espírito', hp:1500, atk:36, def:20, spd:13, region:'final', color:'#a64dff',
   intro:'Eu sou Obsidian. Eu comando a Névoa. Sem memória, vocês não são nada.', skill:'Destruição Total', desc:'O líder dos vilões e a origem da Névoa do Esquecimento. Só pode ser vencido por quem lembra.'},
 ecoVazio:{name:'Eclipse', power:'Manipulação do Tempo', img:'v_eclipse', type:'Mente', hp:900, atk:30, def:15, spd:13, region:'expedicao', color:'#ff3355',
   intro:'Você entrou fundo demais na memória. Aqui, o tempo é meu.', skill:'Tempo Quebrado', desc:'Chefe da Expedição Sankofa. Fica mais forte a cada expedição concluída.'}
};

// ---------------- HISTÓRIA ----------------
// s: speaker id (char id | 'narr' | boss id)
const CHAPTERS = [
 {n:1, title:'As Raízes', region:'brasil', place:'Vila Baobá e Pelourinho, Salvador, Bahia (Brasil)', fact:'Salvador foi a primeira capital do Brasil (1549 a 1763). O Centro Histórico é Patrimônio Mundial da UNESCO desde 1985.', scenes:[
  ['narr','Vila Baobá, Salvador, Bahia. Uma comunidade construída ao redor de um baobá centenário e de uma biblioteca que ninguém sabe exatamente quão antiga é.'],
  ['lider','{P}! Chegou bem na hora. A biblioteca está... estranha.'],
  ['protagonista','Estranha como? A vó sempre disse que ela é "viva", mas eu achava que era força de expressão.'],
  ['lider','Olha esta estante. Ontem aqui estava a história do nosso bloco afro. Hoje, páginas em branco.'],
  ['protagonista','Em branco? Mas eu li esse livro semana passada! Tinha foto da minha mãe desfilando!'],
  ['lider','É a Névoa do Esquecimento. Ela apaga aquilo que deixamos de contar. E está crescendo.'],
  ['narr','Um livro de capa de couro cai da prateleira mais alta. Na capa, um pássaro que olha para trás carregando um ovo: o Sankofa.'],
  ['lider','O Livro Sankofa... sua avó guardava isso. Na língua akan, sankofa quer dizer algo como "volte e pegue". Olhar para o passado para construir o futuro.'],
  ['protagonista','Ele está brilhando! Tem um mapa... Salvador, Tombuctu, Kingston, Nova Orleans...'],
  ['lider','O livro abre portais para as memórias do mundo. Onde a Névoa ataca, alguém precisa ir lá lembrar.'],
  ['capoeirista','Ouvi que tinha confusão na biblioteca! Opa... que fumaça cinza é essa saindo do livro?'],
  ['protagonista','Luana! Ela está chegando. Se prepara!'],
  ['lider','Lembrem: ninguém luta sozinho aqui. Eu sou porque nós somos.']
 ], end:[
  ['capoeirista','A Zara fugiu! E olha, o bloco voltou a tocar!'],
  ['protagonista','As páginas estão voltando! A foto da minha mãe... está aqui de novo.'],
  ['lider','Isso foi só o começo. O livro está apontando para o outro lado do oceano.'],
  ['protagonista','Então vamos. Tem muita história lá fora esperando alguém lembrar.']
 ]},
 {n:2, title:'Além do Oceano', region:'ocidental', region2:'caribe', place:'Tombuctu (Mali), Kingston (Jamaica) e Porto Príncipe (Haiti)', fact:'Tombuctu guardou milhares de manuscritos. Kingston é o berço do ska e do reggae. Em 1804, o Haiti virou a primeira república negra das Américas.', scenes:[
  ['narr','O portal leva o grupo a Tombuctu, no Mali, cidade que foi um dos grandes centros de estudo do mundo, com milhares de manuscritos sobre astronomia, matemática, medicina e direito.'],
  ['cantora','Visitantes pelo livro? Faz muito tempo. Sou Fatou. Minha família canta a história desta terra há gerações.'],
  ['protagonista','Você é uma griot?'],
  ['cantora','Griots guardam a palavra. E tem um mascarado chamado Kemet querendo controlar e apagar os manuscritos.'],
  ['dj','E eu vim de Acra atrás de uma batida que faz a Névoa recuar. Parece que achei a festa certa.'],
  ['protagonista','Depois daqui o livro mostra ilhas... o Caribe. As mesmas batidas, os mesmos tambores, do outro lado do mar.'],
  ['cantora','Porque as histórias viajaram junto com as pessoas. Nenhum oceano apaga isso.']
 ], end:[
  ['chef','Bem-vindos a Porto Príncipe! Sentem, tem soup joumou. É a sopa da nossa independência, de 1804.'],
  ['protagonista','A primeira república negra livre das Américas...'],
  ['chef','Exato. E cada colherada lembra isso. Agora, o livro está brilhando para o norte.']
 ]},
 {n:3, title:'Vozes', region:'eua', place:'Nova Orleans e Bronx, Nova York (EUA)', fact:'O jazz nasceu em Nova Orleans no início do século XX. O hip-hop surgiu no Bronx, numa festa de bairro em 1973.', scenes:[
  ['narr','Nova Orleans. A cidade onde o jazz nasceu, no começo do século XX, misturando blues, ragtime, cantos de igreja e ritmos que vieram da África e do Caribe.'],
  ['musico','Vocês ouviram isso? Nada. Silêncio. Nessa cidade isso é um crime.'],
  ['protagonista','A Névoa está calando a música?'],
  ['musico','Um tal de Vértice hackeou o som da cidade. Hip-hop, jazz, soul... tudo preso num loop.'],
  ['dj','Um loop? Loop é comigo. Mas loop sem criatividade é prisão.'],
  ['musico','Então vamos lá quebrar esse loop. Com estilo.']
 ], end:[
  ['musico','Escuta só... a cidade voltou a tocar.'],
  ['inventor','E eu aproveitei os equipamentos do Vértice pra montar um amplificador. Marcus Bell, prazer. O próximo portal parece... geológico.']
 ]},
 {n:4, title:'Inventores', region:'austral', place:'Grande Zimbábue (Zimbábue)', fact:'Muralhas de granito erguidas entre os séculos XI e XV sem nenhuma argamassa. Patrimônio Mundial da UNESCO desde 1986.', scenes:[
  ['narr','Grande Zimbábue. Muralhas de granito erguidas entre os séculos XI e XV sem nenhuma argamassa, pedra encaixada sobre pedra.'],
  ['pesquisador','Cuidado onde pisam! Cada pedra aqui é uma aula de engenharia. Sou Thabo.'],
  ['engenheiro','Sem argamassa? Com essa precisão? Isso é engenharia de primeira. Vou digitalizar cada pedra.'],
  ['pesquisador','Um brutamontes chamado Colôsso está derrubando as muralhas. Ele não faz ideia de quem as construiu.'],
  ['protagonista','Então a gente lembra por ele. E protege cada pedra.']
 ], end:[
  ['guerreiro','Belo trabalho. Sou Sipho. Treino luta com bastões e ouvi o barulho do Colôsso caindo lá de Durban.'],
  ['pesquisador','O livro agora aponta para as florestas da Colômbia.']
 ]},
 {n:5, title:'Resistência', region:'latina', place:'San Basilio de Palenque (Colômbia)', fact:'Fundado no século XVII por pessoas que se libertaram da escravidão, liderado por Benkos Biohó. É considerado o primeiro povoado livre das Américas.', scenes:[
  ['narr','San Basilio de Palenque, Colômbia. Fundado por pessoas que se libertaram da escravidão no século XVII, liderados por Benkos Biohó. É considerado o primeiro povoado livre das Américas.'],
  ['esportista','Aqui ainda se fala palenquero, uma língua que mistura espanhol com línguas bantas. Meus avós contam que os caminhos da liberdade eram marcados até nos penteados das tranças.'],
  ['protagonista','Tipo os quilombos no Brasil. Palmares, Dandara, Zumbi...'],
  ['esportista','Isso. Comunidades que escolheram ser livres e se organizaram. A Névoa quer apagar essas trilhas.'],
  ['lider','Resistir também é lembrar. Vamos.']
 ], end:[
  ['esportista','As trilhas voltaram. E as crianças voltaram a brincar na praça. Isso é o que importa.'],
  ['protagonista','Próxima parada: as terras altas da Etiópia.']
 ]},
 {n:6, title:'Grandes Conquistas', region:'oriental', place:'Aksum e Lalibela (Etiópia)', fact:'Aksum cunhava moedas próprias e ergueu obeliscos de mais de 20 metros. Em Lalibela, igrejas inteiras foram esculpidas em uma única rocha.', scenes:[
  ['narr','Aksum, Etiópia. Capital de um reino que cunhava as próprias moedas e erguia obeliscos de mais de 20 metros. Mais ao sul, em Lalibela, igrejas inteiras foram esculpidas de cima para baixo em uma única rocha.'],
  ['historiadora','Makeda, historiadora. E sim, meu nome é o mesmo da rainha de Sabá nas tradições etíopes. Não, eu não sou da realeza.'],
  ['artista','E eu sou a Zuri, de Nairóbi. Vim pintar a memória dos maratonistas, das cientistas e das ativistas daqui antes que a Névoa leve embora.'],
  ['protagonista','Tanta coisa construída, conquistada, inventada...'],
  ['historiadora','E o Senhor das Areias tentando convencer todo mundo de que isso é miragem. Clássico.']
 ], end:[
  ['historiadora','Os obeliscos estão de pé. As histórias também.'],
  ['astronauta','Aqui é a Comandante Okafor, de Neo-Axé. Vocês estão sendo chamados para o futuro. Urgente.']
 ]},
 {n:7, title:'O Futuro', region:'futuro', place:'Neo-Axé, cidade afrofuturista (fictícia)', fact:'O termo afrofuturismo foi criado em 1993 pelo crítico Mark Dery para a arte que imagina o futuro a partir da cultura negra.', scenes:[
  ['narr','Neo-Axé. Uma cidade de torres metálicas cobertas por padrões geométricos inspirados em tecidos e esculturas africanas, iluminadas em neon. Aqui se estuda, se dança e se inventa o amanhã.'],
  ['astronauta','Nosso arquivo central guarda tudo que vocês salvaram. Mas a IA que o protege foi corrompida.'],
  ['cientista','Vulcano corrompeu a IA do arquivo. Agora ela acha que memória é "dado desnecessário".'],
  ['protagonista','Então o futuro também pode esquecer?'],
  ['astronauta','O futuro esquece se ninguém o ensinar a lembrar.']
 ], end:[
  ['cientista','Arquivo restaurado. Backups em cinco continentes. Aprendemos a lição.'],
  ['protagonista','Mas a Névoa ainda está saindo de algum lugar... do Livro. Da Vila Baobá.']
 ]},
 {n:8, title:'Nosso Legado', region:'final', place:'Vila Baobá, Salvador, Bahia (Brasil)', fact:'Baobás podem viver mais de mil anos. Em várias culturas africanas, a árvore é símbolo de memória, encontro e sabedoria.', scenes:[
  ['narr','De volta à Vila Baobá. A Névoa se concentra ao redor do baobá centenário. Dela surge Obsidian, o líder de todos os vilões.'],
  ['esquecimento','Eu sou Obsidian. Eu sou o nada entre uma geração e outra. Sem vocês, eu venço sozinho.'],
  ['protagonista','Você venceria sozinho. Mas a gente nunca está sozinho.'],
  ['lider','Todos que vocês conheceram estão aqui, {P}. Olhe ao redor.'],
  ['protagonista','Então vamos lembrar juntos.']
 ], end:[
  ['narr','A Névoa se desfaz em milhares de páginas que voltam, uma a uma, para as estantes.'],
  ['lider','O objetivo nunca foi derrotar a Névoa. Foi garantir que as próximas gerações tenham o que lembrar.'],
  ['protagonista','Então o legado não é o que guardamos. É o que a gente passa adiante.'],
  ['narr','FIM DO CAPÍTULO FINAL. O Livro Sankofa continua aberto: novas expedições, eventos e regiões esperam por você.']
 ]}
];
